-- Made with 'mini.colors' module of https://github.com/nvim-mini/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "minimal_base16_sat"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { link = "DiagnosticError" })
hi(0, "@comment.note", { link = "DiagnosticInfo" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { link = "DiagnosticWarn" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@diff.delta", { link = "Changed" })
hi(0, "@diff.minus", { link = "Removed" })
hi(0, "@diff.plus", { link = "Added" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { nocombine = true, sp = "#cacbd4", underdouble = true })
hi(0, "@markup.heading.2.delimiter.vimdoc", { nocombine = true, sp = "#cacbd4", underline = true })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@neorg.anchors.declaration", { link = "@markup.link.label" })
hi(0, "@neorg.anchors.declaration.delimiter", { link = "NonText" })
hi(0, "@neorg.anchors.definition.delimiter", { link = "NonText" })
hi(0, "@neorg.definitions.content", { link = "@markup.italic" })
hi(0, "@neorg.definitions.prefix", { link = "@punctuation.delimiter" })
hi(0, "@neorg.definitions.suffix", { link = "@punctuation.delimiter" })
hi(0, "@neorg.definitions.title", { link = "@markup.strong" })
hi(0, "@neorg.delimiters.horizontal_line", { link = "@punctuation.delimiter" })
hi(0, "@neorg.delimiters.strong", { link = "@punctuation.delimiter" })
hi(0, "@neorg.delimiters.weak", { link = "@punctuation.delimiter" })
hi(0, "@neorg.error", { link = "Error" })
hi(0, "@neorg.footnotes.content", { link = "@markup.italic" })
hi(0, "@neorg.footnotes.prefix", { link = "@punctuation.delimiter" })
hi(0, "@neorg.footnotes.suffix", { link = "@punctuation.delimiter" })
hi(0, "@neorg.footnotes.title", { link = "@markup.strong" })
hi(0, "@neorg.headings.1.prefix", { link = "@attribute" })
hi(0, "@neorg.headings.1.title", { link = "@attribute" })
hi(0, "@neorg.headings.2.prefix", { link = "@label" })
hi(0, "@neorg.headings.2.title", { link = "@label" })
hi(0, "@neorg.headings.3.prefix", { link = "@constant" })
hi(0, "@neorg.headings.3.title", { link = "@constant" })
hi(0, "@neorg.headings.4.prefix", { link = "@string" })
hi(0, "@neorg.headings.4.title", { link = "@string" })
hi(0, "@neorg.headings.5.prefix", { link = "@label" })
hi(0, "@neorg.headings.5.title", { link = "@label" })
hi(0, "@neorg.headings.6.prefix", { link = "@constructor" })
hi(0, "@neorg.headings.6.title", { link = "@constructor" })
hi(0, "@neorg.links.description", { link = "@markup.link.url" })
hi(0, "@neorg.links.description.delimiter", { link = "NonText" })
hi(0, "@neorg.links.file", { link = "@comment" })
hi(0, "@neorg.links.file.delimiter", { link = "NonText" })
hi(0, "@neorg.links.location.definition", { link = "@neorg.definitions.title" })
hi(0, "@neorg.links.location.definition.prefix", { link = "@neorg.definitions.prefix" })
hi(0, "@neorg.links.location.delimiter", { link = "NonText" })
hi(0, "@neorg.links.location.external_file", { link = "@label" })
hi(0, "@neorg.links.location.external_file.prefix", { link = "@label" })
hi(0, "@neorg.links.location.footnote", { link = "@neorg.footnotes.title" })
hi(0, "@neorg.links.location.footnote.prefix", { link = "@neorg.footnotes.prefix" })
hi(0, "@neorg.links.location.generic", { link = "@type" })
hi(0, "@neorg.links.location.generic.prefix", { link = "@type" })
hi(0, "@neorg.links.location.heading.1", { link = "@neorg.headings.1.title" })
hi(0, "@neorg.links.location.heading.1.prefix", { link = "@neorg.headings.1.prefix" })
hi(0, "@neorg.links.location.heading.2", { link = "@neorg.headings.2.title" })
hi(0, "@neorg.links.location.heading.2.prefix", { link = "@neorg.headings.2.prefix" })
hi(0, "@neorg.links.location.heading.3", { link = "@neorg.headings.3.title" })
hi(0, "@neorg.links.location.heading.3.prefix", { link = "@neorg.headings.3.prefix" })
hi(0, "@neorg.links.location.heading.4", { link = "@neorg.headings.4.title" })
hi(0, "@neorg.links.location.heading.4.prefix", { link = "@neorg.headings.4.prefix" })
hi(0, "@neorg.links.location.heading.5", { link = "@neorg.headings.5.title" })
hi(0, "@neorg.links.location.heading.5.prefix", { link = "@neorg.headings.5.prefix" })
hi(0, "@neorg.links.location.heading.6", { link = "@neorg.headings.6.title" })
hi(0, "@neorg.links.location.heading.6.prefix", { link = "@neorg.headings.6.prefix" })
hi(0, "@neorg.links.location.marker", { link = "@neorg.markers.title" })
hi(0, "@neorg.links.location.marker.prefix", { link = "@neorg.markers.prefix" })
hi(0, "@neorg.links.location.url", { link = "@markup.link.url" })
hi(0, "@neorg.lists.ordered.prefix", { link = "@keyword.repeat" })
hi(0, "@neorg.lists.unordered.prefix", { link = "@markup.list" })
hi(0, "@neorg.markup.bold", { link = "@markup.strong" })
hi(0, "@neorg.markup.bold.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.free_form_delimiter", { link = "NonText" })
hi(0, "@neorg.markup.inline_comment", { fg = "#777790" })
hi(0, "@neorg.markup.inline_comment.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.inline_math", { link = "@markup.math" })
hi(0, "@neorg.markup.inline_math.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.italic", { link = "@markup.italic" })
hi(0, "@neorg.markup.italic.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.spoiler", { link = "@comment.error" })
hi(0, "@neorg.markup.spoiler.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.strikethrough", { link = "@markup.strikethrough" })
hi(0, "@neorg.markup.strikethrough.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.subscript", { link = "@label" })
hi(0, "@neorg.markup.subscript.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.superscript", { link = "@number" })
hi(0, "@neorg.markup.superscript.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.underline", { link = "@markup.underline" })
hi(0, "@neorg.markup.underline.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.variable", { link = "@function.macro" })
hi(0, "@neorg.markup.variable.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.verbatim", { fg = "#9ea1b5" })
hi(0, "@neorg.markup.verbatim.delimiter", { link = "NonText" })
hi(0, "@neorg.modifiers.escape", { link = "@type" })
hi(0, "@neorg.modifiers.link", { link = "NonText" })
hi(0, "@neorg.quotes.1.content", { link = "@punctuation.delimiter" })
hi(0, "@neorg.quotes.1.prefix", { link = "@punctuation.delimiter" })
hi(0, "@neorg.quotes.2.content", { link = "Blue" })
hi(0, "@neorg.quotes.2.prefix", { link = "Blue" })
hi(0, "@neorg.quotes.3.content", { link = "Yellow" })
hi(0, "@neorg.quotes.3.prefix", { link = "Yellow" })
hi(0, "@neorg.quotes.4.content", { link = "Red" })
hi(0, "@neorg.quotes.4.prefix", { link = "Red" })
hi(0, "@neorg.quotes.5.content", { link = "Green" })
hi(0, "@neorg.quotes.5.prefix", { link = "Green" })
hi(0, "@neorg.quotes.6.content", { link = "Brown" })
hi(0, "@neorg.quotes.6.prefix", { link = "Brown" })
hi(0, "@neorg.rendered.latex", { link = "Normal" })
hi(0, "@neorg.selection_window.arrow", { link = "@none" })
hi(0, "@neorg.selection_window.heading", { link = "@annotation" })
hi(0, "@neorg.selection_window.key", { link = "@module" })
hi(0, "@neorg.selection_window.keyname", { link = "@constant" })
hi(0, "@neorg.selection_window.nestedkeyname", { link = "@string" })
hi(0, "@neorg.tags.carryover.begin", { link = "@label" })
hi(0, "@neorg.tags.carryover.name", { link = "@none" })
hi(0, "@neorg.tags.carryover.name.delimiter", { link = "@none" })
hi(0, "@neorg.tags.carryover.name.word", { link = "@label" })
hi(0, "@neorg.tags.carryover.parameters", { link = "@string" })
hi(0, "@neorg.tags.comment.content", { link = "@comment" })
hi(0, "@neorg.tags.ranged_verbatim.begin", { link = "@keyword" })
hi(0, "@neorg.tags.ranged_verbatim.code_block", {})
hi(0, "@neorg.tags.ranged_verbatim.document_meta.array.bracket", { link = "@punctuation.bracket" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.array.value", { link = "@none" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.authors", { link = "@annotation" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.categories", { link = "@keyword" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.created", { link = "@number.float" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.description", { link = "@label" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.key", { link = "@variable.member" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.number", { link = "@number" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.object.bracket", { link = "@punctuation.bracket" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.title", { link = "@markup.heading" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.trailing", { link = "@keyword.repeat" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.updated", { link = "@number.float" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.value", { link = "@string" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.version", { link = "@number.float" })
hi(0, "@neorg.tags.ranged_verbatim.end", { link = "@keyword" })
hi(0, "@neorg.tags.ranged_verbatim.name", { link = "@none" })
hi(0, "@neorg.tags.ranged_verbatim.name.delimiter", { link = "@none" })
hi(0, "@neorg.tags.ranged_verbatim.name.word", { link = "@keyword" })
hi(0, "@neorg.tags.ranged_verbatim.parameters", { link = "@type" })
hi(0, "@neorg.todo_items.cancelled", { link = "NonText" })
hi(0, "@neorg.todo_items.done", { link = "@string" })
hi(0, "@neorg.todo_items.on_hold", { link = "@comment.note" })
hi(0, "@neorg.todo_items.pending", { link = "@module" })
hi(0, "@neorg.todo_items.recurring", { link = "@keyword.repeat" })
hi(0, "@neorg.todo_items.uncertain", { link = "@boolean" })
hi(0, "@neorg.todo_items.undone", { link = "@punctuation.delimiter" })
hi(0, "@neorg.todo_items.urgent", { link = "@comment.error" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@string.escape", { link = "@string.special" })
hi(0, "@string.regexp", { link = "@string.special" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@variable", { fg = "#dee2ee" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Added", { ctermfg = 10, fg = "#a8f9b9" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#7bc1b9" })
hi(0, "BufferCurrent", { bg = "#1a1c1d", fg = "#c8cbdb" })
hi(0, "BufferCurrentIndex", { bg = "#1d1f21", fg = "#c8cbdb" })
hi(0, "BufferCurrentMod", { bg = "#1d1f21", fg = "#dcb45c" })
hi(0, "BufferCurrentSign", { bg = "#1d1f21", fg = "#81aed7" })
hi(0, "BufferCurrentTarget", { bg = "#1d1f21", bold = true, fg = "#d95a6f" })
hi(0, "BufferInactive", { bg = "#1a1c1d", fg = "#71778d" })
hi(0, "BufferInactiveIndex", { bg = "#1a1c1d", fg = "#71778d" })
hi(0, "BufferInactiveMod", { bg = "#1a1c1d", fg = "#dcb45c" })
hi(0, "BufferInactiveSign", { bg = "#1a1c1d", fg = "#71778d" })
hi(0, "BufferInactiveTarget", { bg = "#1a1c1d", bold = true, fg = "#d95a6f" })
hi(0, "BufferLineFill", { bg = "#1a1c1d", bold = true, fg = "#c8cbdb" })
hi(0, "BufferVisible", { bg = "#1d1f21", fg = "#c8cbdb" })
hi(0, "BufferVisibleIndex", { bg = "#1d1f21", fg = "#c8cbdb" })
hi(0, "BufferVisibleMod", { bg = "#1d1f21", fg = "#dcb45c" })
hi(0, "BufferVisibleSign", { bg = "#1d1f21", fg = "#8bc04f" })
hi(0, "BufferVisibleTarget", { bg = "#1d1f21", bold = true, fg = "#d95a6f" })
hi(0, "Changed", { ctermfg = 14, fg = "#76fbfa" })
hi(0, "Character", { fg = "#8bc04f" })
hi(0, "CmpDocumentation", { fg = "#c8cbdb" })
hi(0, "CmpDocumentationBorder", { fg = "#71778d" })
hi(0, "CmpItemAbbr", { fg = "#c8cbdb" })
hi(0, "CmpItemAbbrDefault", { fg = "#c8cbdb" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#4b555f" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#4b555f" })
hi(0, "CmpItemAbbrMatch", { fg = "#81aed7" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#c8cbdb" })
hi(0, "CmpItemAbbrMatchFuzzy", { fg = "#81aed7" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#c8cbdb" })
hi(0, "CmpItemKind", { fg = "#8bc04f" })
hi(0, "CmpItemKindClass", { fg = "#d95a6f" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = "#7bc1b9" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = "#dcb45c" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#d95a6f" })
hi(0, "CmpItemKindEnum", { fg = "#81aed7" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = "#7bc1b9" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = "#c8cbdb" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { fg = "#bc94d4" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#81aed7" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { fg = "#d95a6f" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { fg = "#c8cbdb" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { fg = "#81aed7" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariabl", { fg = "#c8cbdb" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#bc94d4" })
hi(0, "CmpItemMenuDefault", { fg = "#c8cbdb" })
hi(0, "CodeActionMenuDetailsDisabled", { fg = "#4b555f" })
hi(0, "CodeActionMenuDetailsLabel", { fg = "#dcb45c" })
hi(0, "CodeActionMenuDetailsPreferred", { fg = "#8bc04f" })
hi(0, "CodeActionMenuDetailsTitle", { fg = "#c8cbdb" })
hi(0, "CodeActionMenuDetailsUndefined", { fg = "#4b555f" })
hi(0, "CodeActionMenuMenuDisabled", { fg = "#4b555f" })
hi(0, "CodeActionMenuMenuIndex", { fg = "#81aed7" })
hi(0, "CodeActionMenuMenuKind", { fg = "#8bc04f" })
hi(0, "CodeActionMenuMenuSelection", { fg = "#81aed7" })
hi(0, "CodeActionMenuMenuTitle", { fg = "#c8cbdb" })
hi(0, "CodeActionMenuWarningMessageBorder", { fg = "#d95a6f" })
hi(0, "CodeActionMenuWarningMessageText", { fg = "#d5854b" })
hi(0, "ColorColumn", { bg = "#2c2d32" })
hi(0, "Comment", { fg = "#4b555f", italic = true })
hi(0, "Conceal", { fg = "#c8cbdb" })
hi(0, "Conditional", { fg = "#bc94d4" })
hi(0, "Constant", { fg = "#7bc1b9" })
hi(0, "CurSearch", { bg = "#fce094", ctermbg = 11, ctermfg = 0, fg = "#050811" })
hi(0, "Cursor", { bg = "#1d1f21", fg = "#dcb45c" })
hi(0, "CursorColumn", {})
hi(0, "CursorLine", { bold = true, fg = "#bc94d4" })
hi(0, "CursorLineNr", { bold = true, fg = "#c8cbdb" })
hi(0, "DashboardCenter", { fg = "#c8cbdb" })
hi(0, "DashboardFooter", { fg = "#dcb45c" })
hi(0, "DashboardHeader", { fg = "#81aed7" })
hi(0, "Debug", { fg = "#c8cbdb" })
hi(0, "Define", { fg = "#d95a6f" })
hi(0, "Delimiter", { fg = "#c8cbdb" })
hi(0, "DiagnosticError", { ctermfg = 9, fg = "#e5454b" })
hi(0, "DiagnosticFloatingError", { fg = "#e5454b" })
hi(0, "DiagnosticFloatingHint", { fg = "#81aed7" })
hi(0, "DiagnosticFloatingInfo", { fg = "#dcb45c" })
hi(0, "DiagnosticFloatingWarn", { fg = "#d5854b" })
hi(0, "DiagnosticHint", { ctermfg = 12, fg = "#81aed7" })
hi(0, "DiagnosticInfo", { ctermfg = 14, fg = "#dcb45c" })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#a8f9b9" })
hi(0, "DiagnosticSignError", { bg = "#282a2e", fg = "#e5454b" })
hi(0, "DiagnosticSignHint", { bg = "#282a2e", fg = "#81aed7" })
hi(0, "DiagnosticSignInfo", { bg = "#282a2e", fg = "#dcb45c" })
hi(0, "DiagnosticSignWarn", { bg = "#282a2e", fg = "#d5854b" })
hi(0, "DiagnosticVirtualTextError", { fg = "#e5454b" })
hi(0, "DiagnosticVirtualTextHint", { fg = "#71778d" })
hi(0, "DiagnosticVirtualTextInfo", { fg = "#dcb45c" })
hi(0, "DiagnosticVirtualTextWarn", { fg = "#d5854b" })
hi(0, "DiagnosticWarn", { ctermfg = 11, fg = "#d5854b" })
hi(0, "DiffAdd", { bg = "#005523", ctermbg = 10, ctermfg = 0, fg = "#8bc04f" })
hi(0, "DiffAdded", { fg = "#8bc04f" })
hi(0, "DiffChange", { bg = "#4f5258", fg = "#8bc04f" })
hi(0, "DiffDelete", { bold = true, ctermfg = 9, fg = "#d95a6f" })
hi(0, "DiffFile", { fg = "#bc94d4" })
hi(0, "DiffRemoved", { fg = "#d95a6f" })
hi(0, "DiffText", { bg = "#007373", ctermbg = 14, ctermfg = 0, fg = "#c8cbdb" })
hi(0, "DiffViewNormal", { bg = "#1a1c1d", fg = "#71778d" })
hi(0, "DiffviewFilePanelDeletion", { fg = "#e5454b" })
hi(0, "DiffviewFilePanelInsertion", { fg = "#7cdd6f" })
hi(0, "DiffviewStatusAdded", { fg = "#7cdd6f" })
hi(0, "DiffviewStatusDeleted", { fg = "#e5454b" })
hi(0, "DiffviewStatusModified", { fg = "#5cb0c7" })
hi(0, "DiffviewStatusRenamed", { fg = "#5cb0c7" })
hi(0, "DiffviewVertSplit", { bg = "#1d1f21" })
hi(0, "Directory", { ctermfg = 14, fg = "#c8cbdb" })
hi(0, "Error", { bg = "#1d1f21", bold = true, ctermbg = 9, ctermfg = 0, fg = "#d95a6f" })
hi(0, "ErrorMsg", { bg = "#d95555", bold = true, ctermfg = 9, fg = "#222734" })
hi(0, "Exception", { fg = "#c8cbdb" })
hi(0, "EyelinerDimmed", { fg = "#4b555f" })
hi(0, "EyelinerPrimary", { fg = "#7bc1b9" })
hi(0, "EyelinerSecondary", { fg = "#d95a6f" })
hi(0, "Float", { fg = "#d8894e" })
hi(0, "FloatBorder", { fg = "#ffffff" })
hi(0, "FlutterWidgetGuides", { fg = "#71778d" })
hi(0, "FoldColumn", { fg = "#646f86" })
hi(0, "Folded", { bg = "#26272a", fg = "#c8cbdb" })
hi(0, "Function", { ctermfg = 14, fg = "#81aed7" })
hi(0, "GitGutterAdd", { fg = "#7cdd6f" })
hi(0, "GitGutterChange", { fg = "#5cb0c7" })
hi(0, "GitGutterDelete", { fg = "#e5454b" })
hi(0, "GitSignsAdd", { bg = "#282a2e", fg = "#8bc04f" })
hi(0, "GitSignsChange", { bg = "#282a2e", fg = "#5cb0c7" })
hi(0, "GitSignsDelete", { bg = "#282a2e", fg = "#d95a6f" })
hi(0, "Identifier", { ctermfg = 12, fg = "#c8cbdb" })
hi(0, "Ignore", { fg = "#3e4950" })
hi(0, "IncSearch", { bg = "#cf8e5e", fg = "#1a1f24" })
hi(0, "Include", { fg = "#d95a6f" })
hi(0, "IndentBlanklineChar", { fg = "#292d3e" })
hi(0, "IndentBlanklineContextChar", { fg = "#71778d" })
hi(0, "IndentBlanklineSpaceChar", { fg = "#c8cbdb" })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#dcb45c" })
hi(0, "IndentGuidesEven", { fg = "#c8cbdb" })
hi(0, "IndentGuidesOdd", { fg = "#4b555f" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#bc94d4" })
hi(0, "Label", { fg = "#d95a6f" })
hi(0, "LineNr", { fg = "#646f86" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#e5454b" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#81aed7" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#dcb45c" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#dcb45c" })
hi(0, "LspDiagnosticsError", { fg = "#e5454b" })
hi(0, "LspDiagnosticsFloatingError", { fg = "#e5454b" })
hi(0, "LspDiagnosticsFloatingHint", { fg = "#81aed7" })
hi(0, "LspDiagnosticsFloatingInformation", { fg = "#dcb45c" })
hi(0, "LspDiagnosticsFloatingWarning", { fg = "#d5854b" })
hi(0, "LspDiagnosticsHint", { fg = "#81aed7" })
hi(0, "LspDiagnosticsInformation", { fg = "#dcb45c" })
hi(0, "LspDiagnosticsSignError", { fg = "#e5454b" })
hi(0, "LspDiagnosticsSignHint", { fg = "#81aed7" })
hi(0, "LspDiagnosticsSignInformation", { fg = "#dcb45c" })
hi(0, "LspDiagnosticsSignWarning", { fg = "#d5854b" })
hi(0, "LspDiagnosticsUnderlineError", { underline = true })
hi(0, "LspDiagnosticsUnderlineHint", { underline = true })
hi(0, "LspDiagnosticsUnderlineInformation", { underline = true })
hi(0, "LspDiagnosticsUnderlineWarning", { underline = true })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#71778d" })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#dcb45c" })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#d5854b" })
hi(0, "LspDiagnosticsWarning", { fg = "#d5854b" })
hi(0, "LspReferenceRead", { bold = true })
hi(0, "LspReferenceText", { bold = true })
hi(0, "LspReferenceWrite", { bold = true })
hi(0, "Macro", { fg = "#d95a6f" })
hi(0, "MatchParen", { bg = "#1a1c1d", bold = true, fg = "#c8cbdb" })
hi(0, "MatchParenCur", { underline = true })
hi(0, "MatchWord", { underline = true })
hi(0, "MatchWordCur", { underline = true })
hi(0, "ModeMsg", { bg = "#1d1f21", ctermfg = 10, fg = "#c8cbdb" })
hi(0, "MoreMsg", { ctermfg = 14, fg = "#d5854b" })
hi(0, "MsgSeparator", { bg = "#1d1f21", fg = "#c8cbdb" })
hi(0, "NERDTreeBookmark", { fg = "#d8894e" })
hi(0, "NERDTreeBookmarkName", { fg = "#d8894e" })
hi(0, "NERDTreeBookmarksHeader", { fg = "#d95a6f" })
hi(0, "NERDTreeBookmarksLeader", { fg = "#81aed7" })
hi(0, "NERDTreeCWD", { fg = "#d95a6f" })
hi(0, "NERDTreeClosable", { fg = "#d95a6f" })
hi(0, "NERDTreeCurrentNode", { fg = "#4b555f" })
hi(0, "NERDTreeDir", { fg = "#81aed7" })
hi(0, "NERDTreeDirSlash", { fg = "#4b555f" })
hi(0, "NERDTreeExecFile", { fg = "#8bc04f" })
hi(0, "NERDTreeFile", { fg = "#c8cbdb" })
hi(0, "NERDTreeFlags", { fg = "#d95a6f" })
hi(0, "NERDTreeHelpCommand", { fg = "#dcb45c" })
hi(0, "NERDTreeHelpKey", { fg = "#c8cbdb" })
hi(0, "NERDTreeHelpTitle", { fg = "#bc94d4" })
hi(0, "NERDTreeIgnore", { fg = "#4b555f" })
hi(0, "NERDTreeLinkDir", { fg = "#bc94d4" })
hi(0, "NERDTreeLinkFile", { fg = "#8bc04f" })
hi(0, "NERDTreeLinkTarget", { fg = "#81aed7" })
hi(0, "NERDTreeNodeDelimiters", { fg = "#4b555f" })
hi(0, "NERDTreeOpenable", { fg = "#4b555f" })
hi(0, "NERDTreePart", { fg = "#d8894e" })
hi(0, "NERDTreePartFile", { fg = "#81aed7" })
hi(0, "NERDTreeRO", { fg = "#d8894e" })
hi(0, "NERDTreeToggleOff", { fg = "#d8894e" })
hi(0, "NERDTreeToggleOn", { fg = "#8bc04f" })
hi(0, "NERDTreeUp", { fg = "#dcb45c" })
hi(0, "NeogitBranch", { fg = "#bc94d4" })
hi(0, "NeogitDiffAdd", { bg = "#1a1c1d", fg = "#7cdd6f" })
hi(0, "NeogitDiffAddHighlight", { bg = "#1a1c1d", fg = "#7cdd6f" })
hi(0, "NeogitDiffContext", { bg = "#1d1f21", fg = "#bbbbbb" })
hi(0, "NeogitDiffContextHighlight", { bg = "#1d1f21", fg = "#bbbbbb" })
hi(0, "NeogitDiffDelete", { bg = "#1a1c1d", fg = "#e5454b" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#1a1c1d", fg = "#e5454b" })
hi(0, "NeogitHunkHeader", { bg = "#1a1c1d", fg = "#bbbbbb" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#1a1c1d", fg = "#bbbbbb" })
hi(0, "NeogitRemote", { fg = "#bc94d4" })
hi(0, "NonText", { fg = "#71778d" })
hi(0, "Normal", { fg = "#c8cbdb" })
hi(0, "NormalFloat", {})
hi(0, "NormalNC", { fg = "#c8cbdb" })
hi(0, "Number", { fg = "#d8894e" })
hi(0, "NvimTreeCursorLine", { bg = "#2c2d32", fg = "#646f86" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#dcb45c", italic = true })
hi(0, "NvimTreeEndOfBuffer", { fg = "#59656c" })
hi(0, "NvimTreeExecFile", { fg = "#8bc04f" })
hi(0, "NvimTreeFolderIcon", { fg = "#4b555f" })
hi(0, "NvimTreeFolderName", { fg = "#c8cbdb" })
hi(0, "NvimTreeGitDeleted", { fg = "#e5454b" })
hi(0, "NvimTreeGitDirty", { fg = "#7cdd6f" })
hi(0, "NvimTreeGitMerge", { fg = "#5cb0c7" })
hi(0, "NvimTreeGitNew", { fg = "#7cdd6f" })
hi(0, "NvimTreeGitRenamed", { fg = "#5cb0c7" })
hi(0, "NvimTreeGitStaged", { fg = "#7cdd6f" })
hi(0, "NvimTreeImageFile", { fg = "#bc94d4" })
hi(0, "NvimTreeIndentMarker", { fg = "#4b555f" })
hi(0, "NvimTreeNormal", { bg = "#1a1c1d", fg = "#c8cbdb" })
hi(0, "NvimTreeNormalNC", { bg = "#1a1c1d" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#c8cbdb", italic = true })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#dcb45c" })
hi(0, "NvimTreeSpecialFile", { fg = "#d8894e" })
hi(0, "NvimTreeSymlink", { fg = "#dcb45c" })
hi(0, "NvimTreeVertSplit", { fg = "#181c1f" })
hi(0, "Operator", { fg = "#c8cbdb" })
hi(0, "Pmenu", { bg = "#1a1c1d", fg = "#c8cbdb" })
hi(0, "PmenuSbar", { bg = "#26272a" })
hi(0, "PmenuSel", { bg = "#1a1c1d", blend = 0, fg = "#646f86", reverse = true })
hi(0, "PmenuThumb", { bg = "#1a1c1d" })
hi(0, "PreCondit", { fg = "#bc94d4" })
hi(0, "PreProc", { fg = "#81aed7" })
hi(0, "Question", { ctermfg = 14, fg = "#8bc04f" })
hi(0, "QuickFixLine", { ctermfg = 14, fg = "#d5854b" })
hi(0, "Removed", { ctermfg = 9, fg = "#ffbdb5" })
hi(0, "Repeat", { fg = "#bc94d4" })
hi(0, "Search", { bg = "#cf8e5e", ctermbg = 11, ctermfg = 0, fg = "#646f86" })
hi(0, "SignColumn", { fg = "#45526c" })
hi(0, "Special", { ctermfg = 14, fg = "#d95a6f" })
hi(0, "SpecialChar", { fg = "#8bc04f" })
hi(0, "SpecialComment", { fg = "#bc94d4" })
hi(0, "SpecialKey", { bold = true, fg = "#3e4950" })
hi(0, "SpellBad", { fg = "#d95a6f", sp = "#ffc0b9", underline = true })
hi(0, "SpellCap", { fg = "#d8894e", sp = "#fce094", underline = true })
hi(0, "SpellLocal", { fg = "#8bc04f", sp = "#b3f6c0", underline = true })
hi(0, "SpellRare", { fg = "#bc94d4", sp = "#8cf8f7", underline = true })
hi(0, "StartifyBracket", { fg = "#c8cbdb" })
hi(0, "StartifyEndOfBuffer", { fg = "#59656c" })
hi(0, "StartifyFile", { fg = "#81aed7" })
hi(0, "StartifyFooter", { fg = "#bc94d4" })
hi(0, "StartifyHeader", { fg = "#81aed7" })
hi(0, "StartifyNumber", { fg = "#d95a6f" })
hi(0, "StartifyPath", { fg = "#4b555f" })
hi(0, "StartifySection", { fg = "#bc94d4" })
hi(0, "StartifySelect", { fg = "#4b555f" })
hi(0, "StartifySlash", { fg = "#4b555f" })
hi(0, "StartifySpecial", { fg = "#dcb45c" })
hi(0, "StartifyVar", { fg = "#4b555f" })
hi(0, "Statement", { bold = true, fg = "#d95a6f" })
hi(0, "StatusLine", { fg = "#646f86" })
hi(0, "StatusLineNC", { fg = "#646f86" })
hi(0, "StatusLineSeparator", { fg = "#181c1f" })
hi(0, "StatusLineTerm", { bg = "#1a1c1d", fg = "#8bc04f" })
hi(0, "StatusLineTermNC", { bg = "#1a1c1d", fg = "#3e4950" })
hi(0, "StorageClass", { fg = "#d95a6f" })
hi(0, "String", { ctermfg = 10, fg = "#8bc04f" })
hi(0, "Structure", { fg = "#81aed7" })
hi(0, "Substitute", { bg = "#cf8e5e", fg = "#71778d" })
hi(0, "TSAnnotation", { fg = "#dcb45c" })
hi(0, "TSAttribute", { fg = "#c8cbdb" })
hi(0, "TSBoolean", { fg = "#d8894e" })
hi(0, "TSCharacter", { fg = "#dcb45c" })
hi(0, "TSCharacterSpecial", { fg = "#bc94d4" })
hi(0, "TSComment", { fg = "#4b555f", italic = true })
hi(0, "TSConditional", { fg = "#d95a6f" })
hi(0, "TSConstBuiltin", { fg = "#bc94d4" })
hi(0, "TSConstMacro", { fg = "#d95a6f" })
hi(0, "TSConstant", { fg = "#bc94d4" })
hi(0, "TSConstructor", { fg = "#c8cbdb" })
hi(0, "TSDefine", { fg = "#d95a6f" })
hi(0, "TSEmphasis", { italic = true })
hi(0, "TSError", { bg = "#1d1f21", bold = true, fg = "#e5454b" })
hi(0, "TSException", { fg = "#d95a6f" })
hi(0, "TSField", { fg = "#c8cbdb" })
hi(0, "TSFloat", { fg = "#d8894e" })
hi(0, "TSFuncBuiltin", { fg = "#bc94d4" })
hi(0, "TSFuncMacro", { fg = "#81aed7" })
hi(0, "TSFunction", { fg = "#81aed7" })
hi(0, "TSInclude", { fg = "#d95a6f" })
hi(0, "TSKeyword", { fg = "#d95a6f" })
hi(0, "TSKeywordFunction", { fg = "#d95a6f" })
hi(0, "TSKeywordOperator", { fg = "#d95a6f" })
hi(0, "TSKeywordReturn", { fg = "#d95a6f" })
hi(0, "TSLabel", { fg = "#bc94d4" })
hi(0, "TSLiteral", { fg = "#dcb45c" })
hi(0, "TSMethod", { fg = "#81aed7" })
hi(0, "TSNamespace", { fg = "#c8cbdb" })
hi(0, "TSNone", { fg = "#d8894e" })
hi(0, "TSNumber", { fg = "#d8894e" })
hi(0, "TSOperator", { fg = "#d95a6f" })
hi(0, "TSParameter", { fg = "#c8cbdb" })
hi(0, "TSParameterReference", { fg = "#c8cbdb" })
hi(0, "TSProperty", { fg = "#c8cbdb" })
hi(0, "TSPunctBracket", { fg = "#c8cbdb" })
hi(0, "TSPunctDelimiter", { fg = "#c8cbdb" })
hi(0, "TSPunctSpecial", { fg = "#d95a6f" })
hi(0, "TSQueryLinterError", { fg = "#e5454b" })
hi(0, "TSRepeat", { fg = "#d95a6f" })
hi(0, "TSString", { fg = "#8bc04f" })
hi(0, "TSStringEscape", { fg = "#8bc04f" })
hi(0, "TSStringRegex", { fg = "#8bc04f" })
hi(0, "TSStrong", { fg = "#dcb45c" })
hi(0, "TSStructure", { fg = "#d95a6f" })
hi(0, "TSSymbol", { fg = "#c8cbdb" })
hi(0, "TSTag", { fg = "#d95a6f" })
hi(0, "TSTagDelimiter", { fg = "#d95a6f" })
hi(0, "TSText", { fg = "#c8cbdb" })
hi(0, "TSTitle", { bold = true, fg = "#c8cbdb" })
hi(0, "TSTodo", { fg = "#7bc1b9" })
hi(0, "TSType", { fg = "#7bc1b9" })
hi(0, "TSTypeBuiltin", { fg = "#dcb45c" })
hi(0, "TSTypeDefinition", { fg = "#d95a6f" })
hi(0, "TSTypeQualifier", { fg = "#d95a6f" })
hi(0, "TSURI", { fg = "#8bc04f", underline = true })
hi(0, "TSUnderline", { underline = true })
hi(0, "TSVariable", { fg = "#c8cbdb" })
hi(0, "TSVariableBuiltin", { fg = "#bc94d4" })
hi(0, "TabLine", { fg = "#646f86" })
hi(0, "TabLineFill", { fg = "#646f86" })
hi(0, "TabLineSel", { bold = true, fg = "#c8cbdb" })
hi(0, "Tag", { fg = "#646f86" })
hi(0, "TelescopeBorder", { fg = "#888888" })
hi(0, "TelescopeMatching", { fg = "#dcb45c" })
hi(0, "TelescopeNormal", {})
hi(0, "TelescopePromptPrefix", { fg = "#8bc04f" })
hi(0, "TelescopeSelection", { bold = true, fg = "#bc94d4" })
hi(0, "TermCursor", { bg = "#767777", fg = "#646f86", reverse = true })
hi(0, "TermCursorNC", { bg = "#767777", fg = "#646f86" })
hi(0, "Title", { bold = true, fg = "#646f86" })
hi(0, "Todo", { bold = true, fg = "#d95a6f" })
hi(0, "TroubleCode", { fg = "#d5854b" })
hi(0, "TroubleCount", { fg = "#d95a6f" })
hi(0, "TroubleError", { bg = "#6d6f73", fg = "#d95a6f" })
hi(0, "TroubleFile", { fg = "#dcb45c" })
hi(0, "TroubleFoldIcon", { fg = "#81aed7" })
hi(0, "TroubleHint", { fg = "#d5854b" })
hi(0, "TroubleIndent", { fg = "#4b555f" })
hi(0, "TroubleInformation", { fg = "#c8cbdb" })
hi(0, "TroubleLocation", { fg = "#c8cbdb" })
hi(0, "TroubleNormal", { fg = "#c8cbdb" })
hi(0, "TroublePreview", { fg = "#d95a6f" })
hi(0, "TroubleSignError", { fg = "#d95a6f" })
hi(0, "TroubleSignHint", { fg = "#8bc04f" })
hi(0, "TroubleSignInformation", { fg = "#c8cbdb" })
hi(0, "TroubleSignOther", { fg = "#8bc04f" })
hi(0, "TroubleSignWarning", { fg = "#d5854b" })
hi(0, "TroubleSource", { fg = "#81aed7" })
hi(0, "TroubleText", { fg = "#c8cbdb" })
hi(0, "TroubleTextError", { fg = "#d95a6f" })
hi(0, "TroubleTextHint", { fg = "#c8cbdb" })
hi(0, "TroubleTextInformation", { fg = "#81aed7" })
hi(0, "TroubleTextWarning", { fg = "#d5854b" })
hi(0, "TroubleWarning", { fg = "#d5854b" })
hi(0, "Type", { fg = "#dcb45c" })
hi(0, "Typedef", { fg = "#dcb45c" })
hi(0, "Variable", { fg = "#c8cbdb" })
hi(0, "VertSplit", { fg = "#212838" })
hi(0, "Visual", { bg = "#2a2f32", bold = true, ctermbg = 15, ctermfg = 0 })
hi(0, "VisualNOS", { bg = "#464f55", fg = "#405076" })
hi(0, "WarningMsg", { bg = "#1d1f21", ctermfg = 11, fg = "#d5854b" })
hi(0, "WhichKey", { fg = "#81aed7" })
hi(0, "WhichKeyDesc", { fg = "#c8cbdb" })
hi(0, "WhichKeyFloat", { bg = "#1a1c1d" })
hi(0, "WhichKeyGroup", { fg = "#bc94d4" })
hi(0, "WhichKeySeperator", { fg = "#d95a6f" })
hi(0, "Whitespace", { fg = "#59656c" })
hi(0, "WildMenu", { fg = "#c8cbdb" })
hi(0, "WilderDefault", { bg = "#1c1c1c", fg = "#ffffff" })
hi(0, "WilderWildmenuAccent", { bg = "#1c1c1c", bold = true, fg = "#ffffff", underline = true })
hi(0, "WilderWildmenuSelectedAccent", { bold = true, fg = "#c8cbdb", underline = true })
hi(0, "WinBar", { bg = "#07080d", bold = true, fg = "#949eb2" })
hi(0, "WinBarNC", { bg = "#07080d", fg = "#949eb2" })
hi(0, "cmakeArguments", { fg = "#c8cbdb" })
hi(0, "cmakeCommand", { fg = "#c8cbdb" })
hi(0, "cmakeGeneratorExpressions", { fg = "#bc94d4" })
hi(0, "cmakeKWproject", { fg = "#bc94d4" })
hi(0, "cmakeKWuse_mangled_mesa", { fg = "#c8cbdb", italic = true })
hi(0, "cmakeKWvariable_watch", { fg = "#c8cbdb" })
hi(0, "cmakeVariable", { fg = "#c8cbdb" })
hi(0, "debugBreakpoint", { fg = "#d95a6f", reverse = true })
hi(0, "debugPc", { bg = "#cacbd4" })
hi(0, "lCursor", { bg = "#767777", fg = "#646f86" })
hi(0, "markdownBlockquote", { fg = "#bbbbbb" })
hi(0, "markdownBold", { bold = true, fg = "#c8cbdb" })
hi(0, "markdownCode", { fg = "#d8894e" })
hi(0, "markdownCodeBlock", { fg = "#d8894e" })
hi(0, "markdownCodeDelimiter", { fg = "#8bc04f" })
hi(0, "markdownCodeError", { fg = "#e5454b" })
hi(0, "markdownCodeSpecial", { fg = "#d8894e" })
hi(0, "markdownH1", { fg = "#c8cbdb" })
hi(0, "markdownH2", { fg = "#c8cbdb" })
hi(0, "markdownH3", { fg = "#c8cbdb" })
hi(0, "markdownH4", { fg = "#c8cbdb" })
hi(0, "markdownH5", { fg = "#c8cbdb" })
hi(0, "markdownH6", { fg = "#c8cbdb" })
hi(0, "markdownHeadingDelimiter", { fg = "#c8cbdb" })
hi(0, "markdownHeadingRule", { fg = "#bbbbbb" })
hi(0, "markdownId", { fg = "#bc94d4" })
hi(0, "markdownIdDeclaration", { fg = "#c8cbdb" })
hi(0, "markdownIdDelimiter", { fg = "#71778d" })
hi(0, "markdownItalic", { italic = true })
hi(0, "markdownLinkDelimiter", { fg = "#71778d" })
hi(0, "markdownLinkText", { fg = "#c8cbdb" })
hi(0, "markdownListMarker", { fg = "#d95a6f" })
hi(0, "markdownOrderedListMarker", { fg = "#d95a6f" })
hi(0, "markdownRule", { fg = "#bbbbbb" })
hi(0, "markdownUrl", { fg = "#bc94d4", underline = true })
hi(0, "markdownUrlTitleDelimiter", { fg = "#c8cbdb" })
hi(0, "pythonBoolean", { fg = "#c8cbdb" })
hi(0, "pythonConditional", { fg = "#d95a6f" })
hi(0, "pythonException", { fg = "#bc94d4" })
hi(0, "pythonFunction", { fg = "#8bc04f" })
hi(0, "pythonInclude", { fg = "#d95a6f" })
hi(0, "pythonOperator", { fg = "#d95a6f" })
hi(0, "pythonStatement", { fg = "#c8cbdb" })

-- No terminal colors defined
