-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "nordfox-sat"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { bg = "#bf616a", fg = "#1f325b" })
hi(0, "@comment.note", { bg = "#81a1c1", fg = "#1f325b" })
hi(0, "@comment.todo", { bg = "#a3be8c", fg = "#1f325b" })
hi(0, "@comment.warning", { bg = "#ebcb8b", fg = "#1f325b" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant.builtin", { fg = "#ed8361" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@constructor", { fg = "#67c5de" })
hi(0, "@constructor.lua", { fg = "#a0b2d0" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@exception", { link = "Exception" })
hi(0, "@field", { fg = "#6aa2d9" })
hi(0, "@field.rust", { fg = "#a0b2d0" })
hi(0, "@float", { link = "Float" })
hi(0, "@function.builtin", { fg = "#d7485e" })
hi(0, "@function.macro", { fg = "#d7485e" })
hi(0, "@include", { link = "Include" })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.conditional.ternary", { link = "Conditional" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.function", { fg = "#cd7ac1" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { fg = "#a0b2d0" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { fg = "#d7485e" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@label.json", { fg = "#79b0e6" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation.special" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { fg = "#e9576d" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { link = "@error" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@markup", { fg = "#c3d0dc" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.italic", { link = "Italic" })
hi(0, "@markup.link", { bold = true, fg = "#cd7ac1" })
hi(0, "@markup.link.label", { link = "Special" })
hi(0, "@markup.link.url", { fg = "#ed8361", italic = true, underline = true })
hi(0, "@markup.list", { fg = "#71d1eb" })
hi(0, "@markup.list.checked", { fg = "#97c46c" })
hi(0, "@markup.list.unchecked", { fg = "#f7c866" })
hi(0, "@markup.math", { fg = "#79b0e6" })
hi(0, "@markup.quote", { fg = "#a0b2d0" })
hi(0, "@markup.raw", { fg = "#67c5de", italic = true })
hi(0, "@markup.raw.block", { fg = "#d671d3" })
hi(0, "@markup.strikethrough", { fg = "#c3d0dc", strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = "#b9374b" })
hi(0, "@markup.underline", { link = "Underline" })
hi(0, "@module", { fg = "#71d1eb" })
hi(0, "@namespace", { fg = "#71d1eb" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@parameter", { fg = "#71d1eb" })
hi(0, "@property", { fg = "#6aa2d9" })
hi(0, "@punctuation.bracket", { fg = "#a0b2d0" })
hi(0, "@punctuation.delimiter", { fg = "#a0b2d0" })
hi(0, "@punctuation.special", { fg = "#71d1eb" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string.escape", { bold = true, fg = "#fad17c" })
hi(0, "@string.regex", { fg = "#fad17c" })
hi(0, "@string.regexp", { fg = "#fad17c" })
hi(0, "@string.special", { link = "Special" })
hi(0, "@string.special.url", { fg = "#ed8361", italic = true, underline = true })
hi(0, "@tag", { fg = "#cd7ac1" })
hi(0, "@tag.attribute", { fg = "#79b0e6", italic = true })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { fg = "#71d1eb" })
hi(0, "@text", { fg = "#c3d0dc" })
hi(0, "@text.danger", { bg = "#bf616a", fg = "#1f325b" })
hi(0, "@text.diff.add", { link = "diffAdded" })
hi(0, "@text.diff.delete", { link = "diffRemoved" })
hi(0, "@text.emphasis", { link = "Italic" })
hi(0, "@text.literal", { fg = "#67c5de", italic = true })
hi(0, "@text.math", { fg = "#79b0e6" })
hi(0, "@text.note", { bg = "#81a1c1", fg = "#1f325b" })
hi(0, "@text.reference", { bold = true, fg = "#cd7ac1" })
hi(0, "@text.strike", { fg = "#c3d0dc", strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#b9374b" })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.todo", { bg = "#a3be8c", fg = "#1f325b" })
hi(0, "@text.todo.checked", { fg = "#97c46c" })
hi(0, "@text.todo.unchecked", { fg = "#f7c866" })
hi(0, "@text.underline", { link = "Underline" })
hi(0, "@text.warning", { bg = "#ebcb8b", fg = "#1f325b" })
hi(0, "@type.builtin", { fg = "#71d1eb" })
hi(0, "@variable", { fg = "#e2e9f6" })
hi(0, "@variable.builtin", { fg = "#d7485e" })
hi(0, "@variable.member", { fg = "#6aa2d9" })
hi(0, "@variable.parameter", { fg = "#71d1eb" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Added", { ctermfg = 10, fg = "#9cfdb1" })
hi(0, "AerialGuide", { fg = "#4762a3" })
hi(0, "AerialLine", { link = "Search" })
hi(0, "AlphaButtons", { fg = "#67c5de" })
hi(0, "AlphaFooter", { fg = "#6aa2d9" })
hi(0, "AlphaHeader", { fg = "#79b0e6" })
hi(0, "AlphaHeaderLabel", { fg = "#e1724e" })
hi(0, "AlphaShortcut", { fg = "#e1724e" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { link = "Number" })
hi(0, "BufferCurrent", { bg = "#7e8188", fg = "#c3d0dc" })
hi(0, "BufferCurrentIndex", { bg = "#7e8188", fg = "#6aa2d9" })
hi(0, "BufferCurrentMod", { bg = "#7e8188", fg = "#f7c866" })
hi(0, "BufferCurrentSign", { bg = "#7e8188", fg = "#6aa2d9" })
hi(0, "BufferCurrentTarget", { bg = "#7e8188", fg = "#d7485e" })
hi(0, "BufferInactive", { bg = "#232831", fg = "#4d72a3" })
hi(0, "BufferInactiveIndex", { bg = "#232831", fg = "#4d72a3" })
hi(0, "BufferInactiveMod", { bg = "#232831", fg = "#5b5142" })
hi(0, "BufferInactiveSign", { bg = "#232831", fg = "#334982" })
hi(0, "BufferInactiveTarget", { bg = "#232831", fg = "#d7485e" })
hi(0, "BufferTabpage", { bg = "#232831", fg = "#334982" })
hi(0, "BufferTabpages", { bg = "#232831" })
hi(0, "BufferVisible", { bg = "#232831", fg = "#c3d0dc" })
hi(0, "BufferVisibleIndex", { bg = "#232831", fg = "#6aa2d9" })
hi(0, "BufferVisibleMod", { bg = "#232831", fg = "#f7c866" })
hi(0, "BufferVisibleSign", { bg = "#232831", fg = "#6aa2d9" })
hi(0, "BufferVisibleTarget", { bg = "#232831", fg = "#d7485e" })
hi(0, "Changed", { ctermfg = 14, fg = "#5bfefe" })
hi(0, "Character", { link = "String" })
hi(0, "CmpDocumentation", { bg = "#232831", fg = "#c3d0dc" })
hi(0, "CmpDocumentationBorder", { bg = "#232831", fg = "#314a6e" })
hi(0, "CmpItemAbbr", { fg = "#c3d0dc" })
hi(0, "CmpItemAbbrDefault", { fg = "#c3d0dc" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#7080a9", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#4d72a3" })
hi(0, "CmpItemAbbrMatch", { fg = "#79b0e6" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#c3d0dc" })
hi(0, "CmpItemAbbrMatchFuzzy", { fg = "#79b0e6" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#c3d0dc" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "@constant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "Function" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#79b0e6" })
hi(0, "CmpItemKindEnum", { link = "Constant" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "@field" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { link = "Constant" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "@field" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "Constant" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { link = "Identifier" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "@namespace" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { link = "@property" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "Keyword" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#a0b2d0" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "Type" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "@field" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { link = "Constant" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "Keyword" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { link = "@variable" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { link = "Comment" })
hi(0, "CmpItemMenuDefault", { fg = "#c3d0dc" })
hi(0, "CocInlayHint", { bg = "#39404f", fg = "#4d72a3" })
hi(0, "ColorColumn", { bg = "#39404f" })
hi(0, "Comment", { fg = "#4d72a3" })
hi(0, "Conceal", { fg = "#4762a3" })
hi(0, "Conditional", { fg = "#de83d0" })
hi(0, "Constant", { fg = "#ed8361" })
hi(0, "CurSearch", { link = "IncSearch" })
hi(0, "Cursor", { bg = "#cdcecf", fg = "#1f325b" })
hi(0, "CursorColumn", { link = "CursorLine" })
hi(0, "CursorLine", {})
hi(0, "CursorLineNr", { bold = true, fg = "#f7c866" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#97c46c" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#4d72a3" })
hi(0, "DapUIBreakpointsInfo", { fg = "#6aa2d9" })
hi(0, "DapUIBreakpointsPath", { fg = "#71d1eb" })
hi(0, "DapUIDecoration", { fg = "#7080a9" })
hi(0, "DapUIFloatBorder", { link = "FloatBorder" })
hi(0, "DapUILineNumber", { link = "Number" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#e2e9f6" })
hi(0, "DapUINormalNC", { fg = "#c3d0dc" })
hi(0, "DapUIPlayPause", { fg = "#a5ff5e" })
hi(0, "DapUIPlayPauseNC", { bg = "#2e3440", fg = "#a5ff5e" })
hi(0, "DapUIRestart", { fg = "#a5ff5e" })
hi(0, "DapUIRestartNC", { bg = "#2e3440", fg = "#a5ff5e" })
hi(0, "DapUIScope", { fg = "#71d1eb" })
hi(0, "DapUISource", { link = "Keyword" })
hi(0, "DapUIStepBack", { fg = "#00f1f5" })
hi(0, "DapUIStepBackNC", { bg = "#2e3440", fg = "#00f1f5" })
hi(0, "DapUIStepInto", { fg = "#00f1f5" })
hi(0, "DapUIStepIntoNC", { bg = "#2e3440", fg = "#00f1f5" })
hi(0, "DapUIStepOut", { fg = "#00f1f5" })
hi(0, "DapUIStepOutNC", { bg = "#2e3440", fg = "#00f1f5" })
hi(0, "DapUIStepOver", { fg = "#00f1f5" })
hi(0, "DapUIStepOverNC", { bg = "#2e3440", fg = "#00f1f5" })
hi(0, "DapUIStop", { fg = "#f70067" })
hi(0, "DapUIStopNC", { bg = "#2e3440", fg = "#f70067" })
hi(0, "DapUIStoppedThread", { fg = "#71d1eb" })
hi(0, "DapUIThread", { link = "String" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIUnavailable", { fg = "#424242" })
hi(0, "DapUIUnavailableNC", { bg = "#2e3440", fg = "#424242" })
hi(0, "DapUIValue", { fg = "#e2e9f6" })
hi(0, "DapUIVariable", { fg = "#e2e9f6" })
hi(0, "DapUIWatchesEmpty", { fg = "#d7485e" })
hi(0, "DapUIWatchesError", { fg = "#d7485e" })
hi(0, "DapUIWatchesValue", { fg = "#f7c866" })
hi(0, "DapUIWinSelect", { bold = true, ctermfg = 14, fg = "#00f1f5" })
hi(0, "DashboardCenter", { link = "String" })
hi(0, "DashboardFooter", { fg = "#ed8361", italic = true })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortCut", { link = "Identifier" })
hi(0, "Delimiter", { link = "Special" })
hi(0, "DiagnosticError", { fg = "#d7485e" })
hi(0, "DiagnosticHint", { fg = "#97c46c" })
hi(0, "DiagnosticInfo", { fg = "#6aa2d9" })
hi(0, "DiagnosticOk", { fg = "#97c46c" })
hi(0, "DiagnosticUnderlineError", { sp = "#bf616a", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#a3be8c", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#81a1c1", undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#a3be8c", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#ebcb8b", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#4b3d48", fg = "#d7485e" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#45504f", fg = "#97c46c" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#3f4a5a", fg = "#6aa2d9" })
hi(0, "DiagnosticVirtualTextOk", { bg = "#45504f", fg = "#97c46c" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#54524f", fg = "#f7c866" })
hi(0, "DiagnosticWarn", { fg = "#f7c866" })
hi(0, "DiffAdd", { bg = "#3c4548" })
hi(0, "DiffChange", { bg = "#364150" })
hi(0, "DiffDelete", { bg = "#403843" })
hi(0, "DiffText", { bg = "#3d515f" })
hi(0, "Directory", { fg = "#79b0e6" })
hi(0, "EndOfBuffer", { fg = "#1f325b" })
hi(0, "Error", { fg = "#d7485e" })
hi(0, "ErrorMsg", { fg = "#d7485e" })
hi(0, "Exception", { link = "Keyword" })
hi(0, "EyelinerDimmed", { fg = "#4d72a3" })
hi(0, "EyelinerPrimary", { fg = "#ed8361" })
hi(0, "EyelinerSecondary", { fg = "#e47ee3" })
hi(0, "FernBranchText", { fg = "#6aa2d9" })
hi(0, "FidgetTask", { link = "LineNr" })
hi(0, "FidgetTitle", { link = "Title" })
hi(0, "FloatBorder", { fg = "#7080a9" })
hi(0, "FocusedSymbol", { link = "Search" })
hi(0, "FoldColumn", { fg = "#7080a9" })
hi(0, "Folded", { bg = "#39404f", fg = "#7080a9" })
hi(0, "Function", { fg = "#79b0e6" })
hi(0, "GitGutterAdd", { fg = "#97c46c" })
hi(0, "GitGutterChange", { fg = "#f7c866" })
hi(0, "GitGutterDelete", { fg = "#d7485e" })
hi(0, "GitSignsAdd", { fg = "#97c46c" })
hi(0, "GitSignsChange", { fg = "#f7c866" })
hi(0, "GitSignsDelete", { fg = "#d7485e" })
hi(0, "GitSignsStagedAdd", { fg = "#4a6236" })
hi(0, "GitSignsStagedAddCul", { fg = "#4a6236" })
hi(0, "GitSignsStagedAddLn", { bg = "#3c4548" })
hi(0, "GitSignsStagedAddNr", { fg = "#4a6236" })
hi(0, "GitSignsStagedChange", { fg = "#7c6330" })
hi(0, "GitSignsStagedChangeCul", { fg = "#7c6330" })
hi(0, "GitSignsStagedChangeLn", { bg = "#364150" })
hi(0, "GitSignsStagedChangeNr", { fg = "#7c6330" })
hi(0, "GitSignsStagedChangedelete", { fg = "#7c6330" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#7c6330" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#364150" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#7c6330" })
hi(0, "GitSignsStagedDelete", { fg = "#6c232f" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#6c232f" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#6c232f" })
hi(0, "GitSignsStagedTopdelete", { fg = "#6c232f" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#6c232f" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#6c232f" })
hi(0, "GlyphPalette0", { fg = "#2c3f72" })
hi(0, "GlyphPalette1", { fg = "#d7485e" })
hi(0, "GlyphPalette10", { fg = "#a4d873" })
hi(0, "GlyphPalette11", { fg = "#fad17c" })
hi(0, "GlyphPalette12", { fg = "#79b0e6" })
hi(0, "GlyphPalette13", { fg = "#de83d0" })
hi(0, "GlyphPalette14", { fg = "#71d1eb" })
hi(0, "GlyphPalette15", { fg = "#e4ecf9" })
hi(0, "GlyphPalette2", { fg = "#97c46c" })
hi(0, "GlyphPalette3", { fg = "#f7c866" })
hi(0, "GlyphPalette4", { fg = "#6aa2d9" })
hi(0, "GlyphPalette5", { fg = "#cd7ac1" })
hi(0, "GlyphPalette6", { fg = "#67c5de" })
hi(0, "GlyphPalette7", { fg = "#e4ecf9" })
hi(0, "GlyphPalette8", { fg = "#3351a8" })
hi(0, "GlyphPalette9", { fg = "#e9576d" })
hi(0, "HopNextKey", { bold = true, fg = "#67c5de" })
hi(0, "HopNextKey1", { bold = true, fg = "#6aa2d9" })
hi(0, "HopNextKey2", { fg = "#4e8bc1" })
hi(0, "HopUnmatched", { fg = "#4d72a3" })
hi(0, "Identifier", { fg = "#67c5de" })
hi(0, "IncSearch", { bg = "#a3be8c", fg = "#1f325b" })
hi(0, "IndentBlanklineChar", { fg = "#334982" })
hi(0, "IndentBlanklineContextChar", { fg = "#e2e9f6" })
hi(0, "IndentBlanklineContextStart", { sp = "#e5e9f0", underline = true })
hi(0, "IndentBlanklineIndent1", { fg = "#d671d3" })
hi(0, "IndentBlanklineIndent2", { fg = "#6aa2d9" })
hi(0, "IndentBlanklineIndent3", { fg = "#e1724e" })
hi(0, "IndentBlanklineIndent4", { fg = "#67c5de" })
hi(0, "IndentBlanklineIndent5", { fg = "#d7485e" })
hi(0, "IndentBlanklineIndent6", { fg = "#f7c866" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#cd7ac1" })
hi(0, "Label", { link = "Conditional" })
hi(0, "LazyButtonActive", { link = "TabLineSel" })
hi(0, "LazyDimmed", { link = "LineNr" })
hi(0, "LazyProp", { link = "LineNr" })
hi(0, "LeapBackdrop", { fg = "#4d72a3" })
hi(0, "LeapLabelPrimary", { bg = "#d092ce", fg = "#1f325b" })
hi(0, "LeapLabelSecondary", { bg = "#93ccdc", fg = "#1f325b" })
hi(0, "LeapMatch", { bg = "#d092ce", fg = "#1f325b" })
hi(0, "LightspeedGreyWash", { fg = "#4d72a3" })
hi(0, "LineNr", { fg = "#7080a9" })
hi(0, "LspCodeLens", { fg = "#4d72a3" })
hi(0, "LspCodeLensSeparator", { fg = "#7080a9" })
hi(0, "LspFloatWinBorder", { fg = "#7080a9" })
hi(0, "LspFloatWinNormal", { bg = "#232831" })
hi(0, "LspInlayHint", { bg = "#39404f", fg = "#4d72a3" })
hi(0, "LspReferenceRead", { bg = "#3e4a5b" })
hi(0, "LspReferenceText", { bg = "#3e4a5b" })
hi(0, "LspReferenceWrite", { bg = "#3e4a5b" })
hi(0, "LspSagaBorderTitle", { link = "Title" })
hi(0, "LspSagaCodeActionBorder", { fg = "#7080a9" })
hi(0, "LspSagaCodeActionContent", { link = "String" })
hi(0, "LspSagaCodeActionTitle", { link = "Title" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#7080a9" })
hi(0, "LspSagaFinderSelection", { fg = "#314a6e" })
hi(0, "LspSagaHoverBorder", { fg = "#7080a9" })
hi(0, "LspSagaRenameBorder", { fg = "#7080a9" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#d7485e" })
hi(0, "LspSignatureActiveParameter", { fg = "#3f6187" })
hi(0, "LspTroubleCount", { bg = "#7e8188", fg = "#cd7ac1" })
hi(0, "LspTroubleNormal", { bg = "#232831", fg = "#7080a9" })
hi(0, "LspTroubleText", { fg = "#a0b2d0" })
hi(0, "MarkviewBlockQuoteDefault", { fg = "#4d72a3" })
hi(0, "MarkviewBlockQuoteError", { fg = "#d7485e" })
hi(0, "MarkviewBlockQuoteNote", { fg = "#6aa2d9" })
hi(0, "MarkviewBlockQuoteOk", { fg = "#97c46c" })
hi(0, "MarkviewBlockQuoteSpecial", { fg = "#de83d0" })
hi(0, "MarkviewBlockQuoteWarn", { fg = "#f7c866" })
hi(0, "MarkviewCheckboxCancelled", { fg = "#4d72a3" })
hi(0, "MarkviewCheckboxChecked", { fg = "#97c46c" })
hi(0, "MarkviewCheckboxPending", { fg = "#f7c866" })
hi(0, "MarkviewCheckboxProgress", { fg = "#de83d0" })
hi(0, "MarkviewCheckboxStriked", { fg = "#4d72a3", strikethrough = true })
hi(0, "MarkviewCheckboxUnchecked", { fg = "#d7485e" })
hi(0, "MarkviewCode", { bg = "#28283d" })
hi(0, "MarkviewCodeInfo", { bg = "#28283d", fg = "#4d72a3" })
hi(0, "MarkviewGradient1", { fg = "#c9d5ff" })
hi(0, "MarkviewGradient10", { fg = "#79b0e6" })
hi(0, "MarkviewGradient2", { fg = "#c0d1fd" })
hi(0, "MarkviewGradient3", { fg = "#b7cdfa" })
hi(0, "MarkviewGradient4", { fg = "#afc9f7" })
hi(0, "MarkviewGradient5", { fg = "#a7c4f4" })
hi(0, "MarkviewGradient6", { fg = "#9dc1f2" })
hi(0, "MarkviewGradient7", { fg = "#94bdef" })
hi(0, "MarkviewGradient8", { fg = "#8bb8ec" })
hi(0, "MarkviewGradient9", { fg = "#82b4e9" })
hi(0, "MarkviewHeading1", { bg = "#394257", fg = "#79b0e6" })
hi(0, "MarkviewHeading1Sign", { fg = "#79b0e6" })
hi(0, "MarkviewHeading2", { bg = "#394257", fg = "#79b0e6" })
hi(0, "MarkviewHeading2Sign", { fg = "#79b0e6" })
hi(0, "MarkviewHeading3", { bg = "#394257", fg = "#79b0e6" })
hi(0, "MarkviewHeading3Sign", { fg = "#79b0e6" })
hi(0, "MarkviewHeading4", { bg = "#394257", fg = "#79b0e6" })
hi(0, "MarkviewHeading4Sign", { fg = "#79b0e6" })
hi(0, "MarkviewHeading5", { bg = "#394257", fg = "#79b0e6" })
hi(0, "MarkviewHeading5Sign", { fg = "#79b0e6" })
hi(0, "MarkviewHeading6", { bg = "#394257", fg = "#79b0e6" })
hi(0, "MarkviewHeading6Sign", { fg = "#79b0e6" })
hi(0, "MarkviewIcon1", { bg = "#28283d", fg = "#79b0e6" })
hi(0, "MarkviewIcon1Fg", { fg = "#79b0e6" })
hi(0, "MarkviewIcon1Sign", { fg = "#79b0e6" })
hi(0, "MarkviewIcon2", { bg = "#28283d", fg = "#79b0e6" })
hi(0, "MarkviewIcon2Fg", { fg = "#79b0e6" })
hi(0, "MarkviewIcon2Sign", { fg = "#79b0e6" })
hi(0, "MarkviewIcon3", { bg = "#28283d", fg = "#79b0e6" })
hi(0, "MarkviewIcon3Fg", { fg = "#79b0e6" })
hi(0, "MarkviewIcon3Sign", { fg = "#79b0e6" })
hi(0, "MarkviewIcon4", { bg = "#28283d", fg = "#79b0e6" })
hi(0, "MarkviewIcon4Fg", { fg = "#79b0e6" })
hi(0, "MarkviewIcon4Sign", { fg = "#79b0e6" })
hi(0, "MarkviewIcon5", { bg = "#28283d", fg = "#79b0e6" })
hi(0, "MarkviewIcon5Fg", { fg = "#79b0e6" })
hi(0, "MarkviewIcon5Sign", { fg = "#79b0e6" })
hi(0, "MarkviewIcon6", { bg = "#28283d", fg = "#79b0e6" })
hi(0, "MarkviewIcon6Fg", { fg = "#79b0e6" })
hi(0, "MarkviewIcon6Sign", { fg = "#79b0e6" })
hi(0, "MarkviewInlineCode", { bg = "#32324c" })
hi(0, "MarkviewLatexSubscript", { fg = "#ab9262", italic = true })
hi(0, "MarkviewLatexSuperscript", { fg = "#589b62", italic = true })
hi(0, "MarkviewListItemMinus", { fg = "#f7c866" })
hi(0, "MarkviewListItemPlus", { fg = "#97c46c" })
hi(0, "MarkviewListItemStar", { fg = "#6aa2d9" })
hi(0, "MarkviewTableAlignCenter", { fg = "#6aa2d9" })
hi(0, "MarkviewTableAlignLeft", { fg = "#6aa2d9" })
hi(0, "MarkviewTableAlignRight", { fg = "#6aa2d9" })
hi(0, "MarkviewTableBorder", { fg = "#6aa2d9" })
hi(0, "MarkviewTableHeader", { fg = "#6aa2d9" })
hi(0, "MatchParen", { bold = true, fg = "#f7c866" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { link = "LspReferenceText" })
hi(0, "MiniCursorwordCurrent", { link = "LspReferenceText" })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { bg = "#bf616a", fg = "#1a2741" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { bg = "#a3be8c", fg = "#1a2741" })
hi(0, "MiniDiffOverAdd", { link = "DiffAdd" })
hi(0, "MiniDiffOverChange", { link = "DiffText" })
hi(0, "MiniDiffOverContext", { link = "DiffChange" })
hi(0, "MiniDiffOverDelete", { link = "DiffDelete" })
hi(0, "MiniDiffSignAdd", { fg = "#97c46c" })
hi(0, "MiniDiffSignChange", { fg = "#f7c866" })
hi(0, "MiniDiffSignDelete", { fg = "#d7485e" })
hi(0, "MiniFilesBorder", { link = "FloatBorder" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { fg = "#c3d0dc" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { link = "FloatTitle" })
hi(0, "MiniFilesTitleFocused", { bold = true, fg = "#c3d0dc" })
hi(0, "MiniHipatternsFixme", { bg = "#bf616a", bold = true, fg = "#1a2741" })
hi(0, "MiniHipatternsHack", { bg = "#ebcb8b", bold = true, fg = "#1a2741" })
hi(0, "MiniHipatternsNote", { bg = "#81a1c1", bold = true, fg = "#1a2741" })
hi(0, "MiniHipatternsTodo", { bg = "#a3be8c", bold = true, fg = "#1a2741" })
hi(0, "MiniIconsAzure", { fg = "#79b0e6" })
hi(0, "MiniIconsBlue", { fg = "#6aa2d9" })
hi(0, "MiniIconsCyan", { fg = "#67c5de" })
hi(0, "MiniIconsGreen", { fg = "#97c46c" })
hi(0, "MiniIconsGrey", { fg = "#c0cde7" })
hi(0, "MiniIconsOrange", { fg = "#e1724e" })
hi(0, "MiniIconsPurple", { fg = "#cd7ac1" })
hi(0, "MiniIconsRed", { fg = "#d7485e" })
hi(0, "MiniIconsYellow", { fg = "#f7c866" })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { link = "Delimiter" })
hi(0, "MiniJump", { bg = "#b48ead", fg = "#1a2741" })
hi(0, "MiniJump2dDim", { link = "Comment" })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#67c5de" })
hi(0, "MiniJump2dSpotAhead", { bg = "#232831", fg = "#4e8bc1", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { bold = true, fg = "#f7c866" })
hi(0, "MiniMapNormal", { link = "NormalFloat" })
hi(0, "MiniMapSymbolCount", { link = "Special" })
hi(0, "MiniMapSymbolLine", { link = "Title" })
hi(0, "MiniMapSymbolView", { link = "Delimiter" })
hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "FloatBorder" })
hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniPickBorderText", { link = "FloatTitle" })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hi(0, "MiniPickMatchMarked", { link = "Visual" })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#ed8361", italic = true })
hi(0, "MiniStarterHeader", { link = "Title" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { link = "Normal" })
hi(0, "MiniStarterItemBullet", { fg = "#7080a9" })
hi(0, "MiniStarterItemPrefix", { fg = "#d671d3" })
hi(0, "MiniStarterQuery", { fg = "#97c46c" })
hi(0, "MiniStarterSection", { fg = "#d7485e" })
hi(0, "MiniStatuslineDevinfo", { bg = "#39404f", fg = "#a0b2d0" })
hi(0, "MiniStatuslineFileinfo", { bg = "#39404f", fg = "#a0b2d0" })
hi(0, "MiniStatuslineFilename", { link = "StatusLine" })
hi(0, "MiniStatuslineInactive", { link = "StatusLineNC" })
hi(0, "MiniStatuslineModeCommand", { bg = "#ebcb8b", bold = true, fg = "#1a2741" })
hi(0, "MiniStatuslineModeInsert", { bg = "#a3be8c", bold = true, fg = "#1a2741" })
hi(0, "MiniStatuslineModeNormal", { bg = "#88c0d0", bold = true, fg = "#1a2741" })
hi(0, "MiniStatuslineModeOther", { bg = "#81a1c1", bold = true, fg = "#1a2741" })
hi(0, "MiniStatuslineModeReplace", { bg = "#bf616a", bold = true, fg = "#1a2741" })
hi(0, "MiniStatuslineModeVisual", { bg = "#b48ead", bold = true, fg = "#1a2741" })
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#5a657d", bold = true, fg = "#a0b2d0" })
hi(0, "MiniTablineFill", { link = "TabLineFill" })
hi(0, "MiniTablineHidden", { bg = "#39404f", fg = "#7080a9" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#abb1bb", bold = true, fg = "#4762a3" })
hi(0, "MiniTablineModifiedHidden", { bg = "#7e8188", fg = "#293d6f" })
hi(0, "MiniTablineModifiedVisible", { bg = "#abb1bb", fg = "#293d6f" })
hi(0, "MiniTablineTabpagesection", { bg = "#2e3440", bold = true, fg = "#c3d0dc" })
hi(0, "MiniTablineVisible", { bg = "#39404f", fg = "#a0b2d0" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#d7485e" })
hi(0, "MiniTestPass", { bold = true, fg = "#97c46c" })
hi(0, "MiniTrailspace", { bg = "#bf616a" })
hi(0, "ModeMsg", { bold = true, fg = "#f7c866" })
hi(0, "ModesCopy", { bg = "#ebcb8b" })
hi(0, "ModesDelete", { bg = "#bf616a" })
hi(0, "ModesInsert", { bg = "#88c0d0" })
hi(0, "ModesVisual", { bg = "#b48ead" })
hi(0, "MoreMsg", { bold = true, fg = "#6aa2d9" })
hi(0, "NagicIconsOperator", { link = "Operator" })
hi(0, "NavicIconsBoolean", { link = "Boolean" })
hi(0, "NavicIconsClass", { link = "Type" })
hi(0, "NavicIconsConstant", { link = "Constant" })
hi(0, "NavicIconsConstructor", { link = "Function" })
hi(0, "NavicIconsEnum", { link = "Constant" })
hi(0, "NavicIconsEnumMember", { link = "@field" })
hi(0, "NavicIconsEvent", { link = "Constant" })
hi(0, "NavicIconsField", { link = "@field" })
hi(0, "NavicIconsFile", { link = "Directory" })
hi(0, "NavicIconsFunction", { link = "Function" })
hi(0, "NavicIconsInterface", { link = "Constant" })
hi(0, "NavicIconsKey", { link = "Identifier" })
hi(0, "NavicIconsMethod", { link = "Function" })
hi(0, "NavicIconsModule", { link = "@namespace" })
hi(0, "NavicIconsNamespace", { link = "@namespace" })
hi(0, "NavicIconsNull", { link = "Type" })
hi(0, "NavicIconsNumber", { link = "Number" })
hi(0, "NavicIconsObject", { link = "@namespace" })
hi(0, "NavicIconsPackage", { link = "@namespace" })
hi(0, "NavicIconsProperty", { link = "@property" })
hi(0, "NavicIconsString", { link = "String" })
hi(0, "NavicIconsStruct", { link = "Type" })
hi(0, "NavicIconsTypeParameter", { link = "@field" })
hi(0, "NavicIconsVariable", { link = "@variable" })
hi(0, "NavicSeparator", { fg = "#4762a3" })
hi(0, "NavicText", { fg = "#c3d0dc" })
hi(0, "NeoTreeDimText", { link = "Conceal" })
hi(0, "NeoTreeDirectoryIcon", { fg = "#6aa2d9" })
hi(0, "NeoTreeDirectoryName", { fg = "#6aa2d9" })
hi(0, "NeoTreeDotfile", { fg = "#4e8bc1" })
hi(0, "NeoTreeFileName", { fg = "#a0b2d0" })
hi(0, "NeoTreeFileNameOpened", { fg = "#c3d0dc" })
hi(0, "NeoTreeGitAdded", { fg = "#97c46c" })
hi(0, "NeoTreeGitConflict", { fg = "#e1724e", italic = true })
hi(0, "NeoTreeGitDeleted", { fg = "#d7485e" })
hi(0, "NeoTreeGitIgnored", { fg = "#4d72a3" })
hi(0, "NeoTreeGitModified", { fg = "#f7c866" })
hi(0, "NeoTreeGitUntracked", { fg = "#b262a5" })
hi(0, "NeoTreeIndentMarker", { fg = "#4762a3" })
hi(0, "NeoTreeNormal", { bg = "#232831", fg = "#c3d0dc" })
hi(0, "NeoTreeNormalNC", { link = "NeoTreeNormal" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#e1724e" })
hi(0, "NeoTreeSymbolicLinkTarget", { fg = "#bc56b8" })
hi(0, "NeogitBranch", { fg = "#f7c866" })
hi(0, "NeogitDiffAdd", { fg = "#97c46c" })
hi(0, "NeogitDiffAddHighlight", { bg = "#3c4548" })
hi(0, "NeogitDiffContextHighlight", { bg = "#39404f" })
hi(0, "NeogitDiffDelete", { fg = "#d7485e" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#403843" })
hi(0, "NeogitHunkHeader", { bg = "#444c5e", fg = "#6aa2d9" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#3e4a5b", fg = "#6aa2d9" })
hi(0, "NeogitNotificationError", { fg = "#d7485e" })
hi(0, "NeogitNotificationInfo", { fg = "#6aa2d9" })
hi(0, "NeogitNotificationWarning", { fg = "#f7c866" })
hi(0, "NeogitRemote", { fg = "#97c46c" })
hi(0, "NeotestAdapterName", { bold = true, fg = "#d671d3" })
hi(0, "NeotestDir", { fg = "#67c5de" })
hi(0, "NeotestExpandMarker", { link = "Conceal" })
hi(0, "NeotestFailed", { fg = "#d7485e" })
hi(0, "NeotestFile", { fg = "#6aa2d9" })
hi(0, "NeotestFocused", { underline = true })
hi(0, "NeotestIndent", { link = "Conceal" })
hi(0, "NeotestMarked", { bold = true, fg = "#c3d0dc" })
hi(0, "NeotestNamespace", { fg = "#47abc7" })
hi(0, "NeotestPassed", { fg = "#97c46c" })
hi(0, "NeotestRunning", { fg = "#e1724e" })
hi(0, "NeotestSkipped", { fg = "#f7c866" })
hi(0, "NeotestTest", { link = "Normal" })
hi(0, "NonText", { fg = "#4762a3" })
hi(0, "Normal", { fg = "#c3d0dc" })
hi(0, "NormalFloat", { bg = "#232831", fg = "#c3d0dc" })
hi(0, "NormalNC", { fg = "#c3d0dc" })
hi(0, "NotifyBackground", { link = "NormalFloat" })
hi(0, "NotifyDEBUGBorder", { fg = "#5a7f53" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGTitle" })
hi(0, "NotifyDEBUGTitle", { fg = "#97c46c" })
hi(0, "NotifyERRORBorder", { fg = "#893c52" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORTitle" })
hi(0, "NotifyERRORTitle", { fg = "#d7485e" })
hi(0, "NotifyINFOBorder", { fg = "#466a98" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOTitle" })
hi(0, "NotifyINFOTitle", { fg = "#6aa2d9" })
hi(0, "NotifyTRACEBorder", { fg = "#4762a3" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACETitle" })
hi(0, "NotifyTRACETitle", { fg = "#4d72a3" })
hi(0, "NotifyWARNBorder", { fg = "#947d4f" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNTitle" })
hi(0, "NotifyWARNTitle", { fg = "#f7c866" })
hi(0, "Number", { fg = "#e1724e" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#7080a9" })
hi(0, "NvimTreeFolderIcon", { fg = "#6aa2d9" })
hi(0, "NvimTreeFolderName", { fg = "#6aa2d9" })
hi(0, "NvimTreeGitDeleted", { fg = "#d7485e" })
hi(0, "NvimTreeGitDirty", { fg = "#f7c866" })
hi(0, "NvimTreeGitMerge", { fg = "#e1724e" })
hi(0, "NvimTreeGitNew", { fg = "#97c46c" })
hi(0, "NvimTreeGitRenamed", { link = "NvimTreeGitDeleted" })
hi(0, "NvimTreeGitStaged", { link = "NvimTreeGitStaged" })
hi(0, "NvimTreeImageFile", { fg = "#b3c3e5" })
hi(0, "NvimTreeIndentMarker", { fg = "#4762a3" })
hi(0, "NvimTreeNormal", { bg = "#232831", fg = "#c3d0dc" })
hi(0, "NvimTreeOpenedFile", { fg = "#e47ee3" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#79b0e6" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#e1724e" })
hi(0, "NvimTreeSpecialFile", { fg = "#67c5de" })
hi(0, "NvimTreeSymlink", { fg = "#bc56b8" })
hi(0, "NvimTreeVertSplit", { link = "VertSplit" })
hi(0, "Operator", { fg = "#a0b2d0" })
hi(0, "Pmenu", { bg = "#3e4a5b", fg = "#c3d0dc" })
hi(0, "PmenuSel", { bg = "#4f6074" })
hi(0, "PmenuThumb", { bg = "#4f6074" })
hi(0, "PounceAccept", { bg = "#d89079", fg = "#1f325b" })
hi(0, "PounceAcceptBest", { bg = "#93ccdc", fg = "#1f325b" })
hi(0, "PounceGap", { bg = "#3e4a5b", fg = "#c3d0dc" })
hi(0, "PounceMatch", { bg = "#4f6074", fg = "#c3d0dc" })
hi(0, "PreProc", { fg = "#e47ee3" })
hi(0, "Question", { link = "MoreMsg" })
hi(0, "QuickFixLine", { link = "CursorLine" })
hi(0, "Removed", { ctermfg = 9, fg = "#ffbab2" })
hi(0, "Repeat", { link = "Conditional" })
hi(0, "Search", { bg = "#4f6074", fg = "#c3d0dc" })
hi(0, "SignColumn", { fg = "#7080a9" })
hi(0, "SignColumnSB", { link = "SignColumn" })
hi(0, "SignifySignAdd", { fg = "#97c46c" })
hi(0, "SignifySignChange", { fg = "#f7c866" })
hi(0, "SignifySignDelete", { fg = "#d7485e" })
hi(0, "Sneak", { bg = "#b48ead", fg = "#1a2741" })
hi(0, "SneakScope", { bg = "#3e4a5b" })
hi(0, "Special", { fg = "#79b0e6" })
hi(0, "SpecialKey", { link = "NonText" })
hi(0, "SpellBad", { sp = "#bf616a", undercurl = true })
hi(0, "SpellCap", { sp = "#ebcb8b", undercurl = true })
hi(0, "SpellLocal", { sp = "#81a1c1", undercurl = true })
hi(0, "SpellRare", { sp = "#81a1c1", undercurl = true })
hi(0, "Statement", { fg = "#cd7ac1" })
hi(0, "StatusLine", { fg = "#a0b2d0" })
hi(0, "StatusLineNC", { fg = "#7080a9" })
hi(0, "String", { fg = "#97c46c" })
hi(0, "Substitute", { bg = "#bf616a", fg = "#1f325b" })
hi(0, "SymbolOutlineConnector", { link = "Conceal" })
hi(0, "TSRainbowBlue", { fg = "#6aa2d9" })
hi(0, "TSRainbowCyan", { fg = "#67c5de" })
hi(0, "TSRainbowGreen", { fg = "#97c46c" })
hi(0, "TSRainbowOrange", { fg = "#e1724e" })
hi(0, "TSRainbowRed", { fg = "#d7485e" })
hi(0, "TSRainbowViolet", { fg = "#cd7ac1" })
hi(0, "TSRainbowYellow", { fg = "#f7c866" })
hi(0, "TabLine", { bg = "#39404f", fg = "#a0b2d0" })
hi(0, "TabLineFill", { bg = "#232831" })
hi(0, "TabLineSel", { bg = "#7e8188", fg = "#1f325b" })
hi(0, "TelescopeBorder", { fg = "#4762a3" })
hi(0, "TelescopeMatching", { link = "Search" })
hi(0, "TelescopeSelection", { link = "CursorLine" })
hi(0, "TelescopeSelectionCaret", { fg = "#97c46c" })
hi(0, "Title", { bold = true, fg = "#79b0e6" })
hi(0, "Todo", { fg = "#1f325b" })
hi(0, "Type", { fg = "#f7c866" })
hi(0, "Visual", { bg = "#3e4a5b" })
hi(0, "WarningMsg", { fg = "#f7c866" })
hi(0, "WhichKey", { link = "Identifier" })
hi(0, "WhichKeyDesc", { link = "Keyword" })
hi(0, "WhichKeyFloat", { link = "NormalFloat" })
hi(0, "WhichKeyGroup", { link = "Function" })
hi(0, "WhichKeySeparator", { link = "Comment" })
hi(0, "WhichKeySeperator", { link = "Comment" })
hi(0, "WhichKeyValue", { link = "Comment" })
hi(0, "Whitespace", { fg = "#334982" })
hi(0, "WildMenu", { link = "Pmenu" })
hi(0, "WilderWildmenuAccent", { bold = true, fg = "#a0b2d0", underline = true })
hi(0, "WilderWildmenuSelectedAccent", { bg = "#3e4a5b", bold = true, fg = "#c3d0dc", underline = true })
hi(0, "WinBar", { bg = "#2e3440", bold = true, fg = "#7080a9" })
hi(0, "WinBarNC", { bg = "#2e3440", bold = true, fg = "#7080a9" })
hi(0, "WinSeparator", { fg = "#1a2741" })
hi(0, "diffAdded", { fg = "#97c46c" })
hi(0, "diffChanged", { fg = "#f7c866" })
hi(0, "diffFile", { fg = "#6aa2d9" })
hi(0, "diffIndexLine", { fg = "#e47ee3" })
hi(0, "diffLine", { fg = "#ed8361" })
hi(0, "diffNewFile", { fg = "#97c46c" })
hi(0, "diffOldFile", { fg = "#f7c866" })
hi(0, "diffRemoved", { fg = "#d7485e" })
hi(0, "illuminatedWordRead", { link = "LspReferenceText" })
hi(0, "illuminatedWordText", { link = "LspReferenceText" })
hi(0, "illuminatedWordWrite", { link = "LspReferenceText" })
hi(0, "lCursor", { link = "Cursor" })
hi(0, "qfFileName", { link = "Directory" })
hi(0, "qfLineNr", { link = "LineNr" })
hi(0, "rainbowcol1", { fg = "#d7485e" })
hi(0, "rainbowcol2", { fg = "#f7c866" })
hi(0, "rainbowcol3", { fg = "#97c46c" })
hi(0, "rainbowcol4", { fg = "#6aa2d9" })
hi(0, "rainbowcol5", { fg = "#67c5de" })
hi(0, "rainbowcol6", { fg = "#cd7ac1" })
hi(0, "rainbowcol7", { fg = "#d671d3" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#3b4252"
g.terminal_color_1 = "#bf616a"
g.terminal_color_2 = "#a3be8c"
g.terminal_color_3 = "#ebcb8b"
g.terminal_color_4 = "#81a1c1"
g.terminal_color_5 = "#b48ead"
g.terminal_color_6 = "#88c0d0"
g.terminal_color_7 = "#e5e9f0"
g.terminal_color_8 = "#465780"
g.terminal_color_9 = "#d06f79"
g.terminal_color_10 = "#b1d196"
g.terminal_color_11 = "#f0d399"
g.terminal_color_12 = "#8cafd2"
g.terminal_color_13 = "#c895bf"
g.terminal_color_14 = "#93ccdc"
g.terminal_color_15 = "#e7ecf4"
