-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "vscode-sat"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { fg = "#dddd9b" })
hi(0, "@attribute", { fg = "#dddd9b" })
hi(0, "@attribute.builtin", { fg = "#34ccb0" })
hi(0, "@boolean", { fg = "#489ce0" })
hi(0, "@character", { fg = "#d78c6d" })
hi(0, "@comment", { fg = "#639b49" })
hi(0, "@comment.error", { bold = true, fg = "#fe343c" })
hi(0, "@comment.note", { bold = true, fg = "#34ccb0" })
hi(0, "@comment.warning", { bold = true, fg = "#dcb96e" })
hi(0, "@conditional", { link = "@keyword.conditional" })
hi(0, "@constant", { fg = "#4ec1ff" })
hi(0, "@constant.builtin", { fg = "#489ce0" })
hi(0, "@constant.macro", { fg = "#34ccb0" })
hi(0, "@constructor", { fg = "#489ce0" })
hi(0, "@constructor.python", { fg = "#34ccb0" })
hi(0, "@decorator", { link = "Identifier" })
hi(0, "@define", { fg = "#cf7dc9" })
hi(0, "@diff.delta", { link = "DiffChange" })
hi(0, "@diff.minus", { link = "DiffDelete" })
hi(0, "@diff.plus", { link = "DiffAdd" })
hi(0, "@error", { fg = "#fe343c" })
hi(0, "@event", { link = "Identifier" })
hi(0, "@exception", { link = "@keyword.exception" })
hi(0, "@field", { link = "@variable.member" })
hi(0, "@float", { link = "@number.float" })
hi(0, "@function", { fg = "#dddd9b" })
hi(0, "@function.builtin", { fg = "#dddd9b" })
hi(0, "@function.macro", { fg = "#dddd9b" })
hi(0, "@function.method", { fg = "#dddd9b" })
hi(0, "@include", { link = "@keyword.import" })
hi(0, "@interface", { link = "Identifier" })
hi(0, "@keyword", { fg = "#489ce0" })
hi(0, "@keyword.conditional", { fg = "#cf7dc9" })
hi(0, "@keyword.exception", { fg = "#cf7dc9" })
hi(0, "@keyword.import", { fg = "#cf7dc9" })
hi(0, "@keyword.repeat", { fg = "#cf7dc9" })
hi(0, "@keyword.return", { fg = "#cf7dc9" })
hi(0, "@label", { fg = "#98dcff" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.comment.c", { fg = "#554f4a" })
hi(0, "@lsp.type.comment.cpp", { fg = "#554f4a" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant" })
hi(0, "@lsp.type.member", { link = "@function" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type" })
hi(0, "@lsp.typemod.keyword.controlFlow", { fg = "#cf7dc9" })
hi(0, "@lsp.typemod.property.readonly", { link = "@constant" })
hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.variable.constant", { link = "@constant" })
hi(0, "@lsp.typemod.variable.readonly", { link = "@constant" })
hi(0, "@markup.heading", { bold = true, fg = "#489ce0" })
hi(0, "@markup.italic", { fg = "#d4d4d4", italic = true })
hi(0, "@markup.link.label", { fg = "#98dcff" })
hi(0, "@markup.link.url", { fg = "#d4d4d4" })
hi(0, "@markup.list.checked", { link = "Todo" })
hi(0, "@markup.list.unchecked", { link = "Todo" })
hi(0, "@markup.raw", { fg = "#d4d4d4" })
hi(0, "@markup.raw.markdown", { fg = "#d78c6d" })
hi(0, "@markup.raw.markdown_inline", { fg = "#d78c6d" })
hi(0, "@markup.strikethrough", { fg = "#d4d4d4", strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = "#489ce0" })
hi(0, "@markup.underline", { fg = "#dcb96e", underline = true })
hi(0, "@method", { link = "@function.method" })
hi(0, "@modifier", { link = "Identifier" })
hi(0, "@module", { fg = "#34ccb0" })
hi(0, "@namespace", { link = "@module" })
hi(0, "@number", { fg = "#aed19b" })
hi(0, "@number.float", { fg = "#aed19b" })
hi(0, "@operator", { fg = "#d4d4d4" })
hi(0, "@parameter", { link = "@variable.parameter" })
hi(0, "@property", { fg = "#98dcff" })
hi(0, "@punctuation.bracket", { fg = "#d4d4d4" })
hi(0, "@punctuation.delimiter", { fg = "#d4d4d4" })
hi(0, "@punctuation.special", { fg = "#d4d4d4" })
hi(0, "@regexp", { fg = "#fe343c" })
hi(0, "@repeat", { link = "@keyword.repeat" })
hi(0, "@storageclass", { link = "@keyword.storage" })
hi(0, "@string", { fg = "#d78c6d" })
hi(0, "@string.regex", { link = "@string.regexp" })
hi(0, "@string.regexp", { fg = "#d78c6d" })
hi(0, "@stringEscape", { bold = true, fg = "#d78c6d" })
hi(0, "@structure", { fg = "#98dcff" })
hi(0, "@tag", { fg = "#489ce0" })
hi(0, "@tag.attribute", { fg = "#98dcff" })
hi(0, "@tag.builtin", { fg = "#489ce0" })
hi(0, "@tag.delimiter", { fg = "#808080" })
hi(0, "@text", { fg = "#d4d4d4" })
hi(0, "@text.danger", { link = "@comment.error" })
hi(0, "@text.diff.add", { link = "@diff.plus" })
hi(0, "@text.diff.delete", { link = "@diff.minus" })
hi(0, "@text.emphasis", { link = "@markup.italic" })
hi(0, "@text.literal", { link = "@markup.raw" })
hi(0, "@text.note", { link = "@comment.note" })
hi(0, "@text.strike", { link = "@markup.strikethrough" })
hi(0, "@text.strong", { link = "@markup.strong" })
hi(0, "@text.title", { link = "@markup.heading" })
hi(0, "@text.underline", { link = "@markup.underline" })
hi(0, "@text.uri", { link = "@markup.link.url" })
hi(0, "@text.warning", { link = "@comment.warning" })
hi(0, "@textReference", { fg = "#d78c6d" })
hi(0, "@type", { fg = "#34ccb0" })
hi(0, "@type.builtin", { fg = "#489ce0" })
hi(0, "@type.builtin.tsx", { link = "@type" })
hi(0, "@type.builtin.typescript", { link = "@type" })
hi(0, "@type.qualifier", { fg = "#489ce0" })
hi(0, "@variable", { fg = "#98dcff" })
hi(0, "@variable.builtin", { fg = "#489ce0" })
hi(0, "@variable.member", { fg = "#98dcff" })
hi(0, "@variable.parameter", { fg = "#98dcff" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "@variable.parameter.reference", { fg = "#98dcff" })
hi(0, "Added", { ctermfg = 10, fg = "#aaf9ba" })
hi(0, "Boolean", { fg = "#489ce0" })
hi(0, "BufferCurrent", { bg = "#1f1f1f", fg = "#d4d4d4" })
hi(0, "BufferCurrentIndex", { bg = "#1f1f1f", fg = "#d4d4d4" })
hi(0, "BufferCurrentMod", { bg = "#1f1f1f", fg = "#dcb96e" })
hi(0, "BufferCurrentSign", { bg = "#1f1f1f", fg = "#d4d4d4" })
hi(0, "BufferCurrentTarget", { bg = "#1f1f1f", fg = "#fe343c" })
hi(0, "BufferInactive", { bg = "#2d2d2d", fg = "#808080" })
hi(0, "BufferInactiveIndex", { bg = "#2d2d2d", fg = "#808080" })
hi(0, "BufferInactiveMod", { bg = "#2d2d2d", fg = "#dcb96e" })
hi(0, "BufferInactiveSign", { bg = "#2d2d2d", fg = "#808080" })
hi(0, "BufferInactiveTarget", { bg = "#2d2d2d", fg = "#fe343c" })
hi(0, "BufferLineBackground", { fg = "#639b49" })
hi(0, "BufferLineBuffer", { fg = "#639b49" })
hi(0, "BufferLineBufferSelected", { bold = true, fg = "#d4d4d4" })
hi(0, "BufferLineBufferVisible", { fg = "#639b49" })
hi(0, "BufferLineCloseButton", { fg = "#639b49" })
hi(0, "BufferLineCloseButtonSelected", { fg = "#d4d4d4" })
hi(0, "BufferLineCloseButtonVisible", { fg = "#639b49" })
hi(0, "BufferLineDiagnostic", { fg = "#4a7436" })
hi(0, "BufferLineDiagnosticSelected", { bold = true, fg = "#9f9f9f" })
hi(0, "BufferLineDiagnosticVisible", { fg = "#4a7436" })
hi(0, "BufferLineDuplicate", { fg = "#5e9345" })
hi(0, "BufferLineDuplicateSelected", { fg = "#5e9345" })
hi(0, "BufferLineDuplicateVisible", { fg = "#5e9345" })
hi(0, "BufferLineError", { fg = "#639b49", sp = "#f44747" })
hi(0, "BufferLineErrorDiagnostic", { fg = "#4a7436", sp = "#b73535" })
hi(0, "BufferLineErrorDiagnosticSelected", { bold = true, fg = "#bf262c", sp = "#b73535" })
hi(0, "BufferLineErrorDiagnosticVisible", { fg = "#4a7436" })
hi(0, "BufferLineErrorSelected", { bold = true, fg = "#fe343c", sp = "#f44747" })
hi(0, "BufferLineErrorVisible", { fg = "#639b49" })
hi(0, "BufferLineFill", { fg = "#639b49" })
hi(0, "BufferLineGroupLabel", { bg = "#6a9955" })
hi(0, "BufferLineGroupSeparator", { fg = "#639b49" })
hi(0, "BufferLineHint", { fg = "#639b49", sp = "#569cd6" })
hi(0, "BufferLineHintDiagnostic", { fg = "#4a7436", sp = "#4075a0" })
hi(0, "BufferLineHintDiagnosticSelected", { bold = true, fg = "#3575a7", sp = "#4075a0" })
hi(0, "BufferLineHintDiagnosticVisible", { fg = "#4a7436" })
hi(0, "BufferLineHintSelected", { bold = true, fg = "#489ce0", sp = "#569cd6" })
hi(0, "BufferLineHintVisible", { fg = "#639b49" })
hi(0, "BufferLineIndicatorSelected", { fg = "#24242d" })
hi(0, "BufferLineInfo", { fg = "#639b49", sp = "#569cd6" })
hi(0, "BufferLineInfoDiagnostic", { fg = "#4a7436", sp = "#4075a0" })
hi(0, "BufferLineInfoDiagnosticSelected", { bold = true, fg = "#3575a7", sp = "#4075a0" })
hi(0, "BufferLineInfoDiagnosticVisible", { fg = "#4a7436" })
hi(0, "BufferLineInfoSelected", { bold = true, fg = "#489ce0", sp = "#569cd6" })
hi(0, "BufferLineInfoVisible", { fg = "#639b49" })
hi(0, "BufferLineModified", { fg = "#d78c6d" })
hi(0, "BufferLineModifiedSelected", { fg = "#d78c6d" })
hi(0, "BufferLineModifiedVisible", { fg = "#d78c6d" })
hi(0, "BufferLineNumbers", { fg = "#639b49" })
hi(0, "BufferLineNumbersSelected", { bold = true, fg = "#d4d4d4" })
hi(0, "BufferLineNumbersVisible", { fg = "#639b49" })
hi(0, "BufferLineOffsetSeparator", { fg = "#444444" })
hi(0, "BufferLinePick", { bold = true, fg = "#fe343c" })
hi(0, "BufferLinePickSelected", { bold = true, fg = "#fe343c" })
hi(0, "BufferLinePickVisible", { bold = true, fg = "#fe343c" })
hi(0, "BufferLineTab", { fg = "#639b49" })
hi(0, "BufferLineTabClose", { fg = "#639b49" })
hi(0, "BufferLineTabSelected", { fg = "#1f1f1f" })
hi(0, "BufferLineTruncMarker", { fg = "#639b49" })
hi(0, "BufferLineWarning", { fg = "#639b49", sp = "#dcdcaa" })
hi(0, "BufferLineWarningDiagnostic", { fg = "#4a7436", sp = "#a5a57f" })
hi(0, "BufferLineWarningDiagnosticSelected", { bold = true, fg = "#a6a674", sp = "#a5a57f" })
hi(0, "BufferLineWarningDiagnosticVisible", { fg = "#4a7436" })
hi(0, "BufferLineWarningSelected", { bold = true, fg = "#dddd9b", sp = "#dcdcaa" })
hi(0, "BufferLineWarningVisible", { fg = "#639b49" })
hi(0, "BufferTabpage", { bg = "#2d2d2d", fg = "#d4d4d4" })
hi(0, "BufferTabpageFill", { bg = "#2d2d2d", fg = "#d4d4d4" })
hi(0, "BufferTabpages", { bg = "#2d2d2d", fg = "#d4d4d4" })
hi(0, "BufferTabpagesFill", { bg = "#2d2d2d", fg = "#d4d4d4" })
hi(0, "BufferVisible", { bg = "#1f1f1f", fg = "#808080" })
hi(0, "BufferVisibleIndex", { bg = "#1f1f1f", fg = "#808080" })
hi(0, "BufferVisibleMod", { bg = "#1f1f1f", fg = "#dcb96e" })
hi(0, "BufferVisibleSign", { bg = "#1f1f1f", fg = "#808080" })
hi(0, "BufferVisibleTarget", { bg = "#1f1f1f", fg = "#fe343c" })
hi(0, "Changed", { ctermfg = 14, fg = "#7afbfa" })
hi(0, "Character", { fg = "#d78c6d" })
hi(0, "CmpItemAbbr", { fg = "#d4d4d4" })
hi(0, "CmpItemAbbrDeprecated", { bg = "#272727", fg = "#554f4a", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#14a2ff" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#14a2ff" })
hi(0, "CmpItemKind", { link = "Pmenu" })
hi(0, "CmpItemKindClass", { link = "CmpItemKindConstructor" })
hi(0, "CmpItemKindColor", { link = "cssColor" })
hi(0, "CmpItemKindConstant", { link = "@constant" })
hi(0, "CmpItemKindConstructor", { fg = "#f78800" })
hi(0, "CmpItemKindEnum", { link = "@variable.member" })
hi(0, "CmpItemKindEnumMember", { link = "@variable.member" })
hi(0, "CmpItemKindEvent", { link = "@constant" })
hi(0, "CmpItemKindField", { link = "@variable.member" })
hi(0, "CmpItemKindFile", { link = "@text.uri" })
hi(0, "CmpItemKindFolder", { link = "@text.uri" })
hi(0, "CmpItemKindFunction", { fg = "#cf7dc9" })
hi(0, "CmpItemKindInterface", { fg = "#98dcff" })
hi(0, "CmpItemKindKeyword", { fg = "#d4d4d4" })
hi(0, "CmpItemKindMethod", { fg = "#cf7dc9" })
hi(0, "CmpItemKindModule", { link = "CmpItemKindKeyword" })
hi(0, "CmpItemKindOperator", { link = "@operator" })
hi(0, "CmpItemKindProperty", { fg = "#d4d4d4" })
hi(0, "CmpItemKindReference", { link = "@variable.parameter.reference" })
hi(0, "CmpItemKindSnippet", { link = "@text" })
hi(0, "CmpItemKindStruct", { link = "@structure" })
hi(0, "CmpItemKindText", { fg = "#98dcff" })
hi(0, "CmpItemKindTypeParameter", { link = "@variable.parameter" })
hi(0, "CmpItemKindUnit", { fg = "#d4d4d4" })
hi(0, "CmpItemKindValue", { link = "@variable.member" })
hi(0, "CmpItemKindVariable", { fg = "#98dcff" })
hi(0, "CmpItemMenu", { fg = "#bbbbbb" })
hi(0, "CocHighlightRead", { bg = "#343b41" })
hi(0, "CocHighlightText", { bg = "#343b41" })
hi(0, "CocHighlightWrite", { bg = "#343b41" })
hi(0, "ColorColumn", { bg = "#222222" })
hi(0, "Comment", { fg = "#639b49" })
hi(0, "CompeDocumentation", { link = "Pmenu" })
hi(0, "CompeDocumentationBorder", { link = "Pmenu" })
hi(0, "Conceal", { fg = "#d4d4d4" })
hi(0, "Conditional", { fg = "#cf7dc9" })
hi(0, "Constant", { fg = "#489ce0" })
hi(0, "CurSearch", { bg = "#fce094", ctermbg = 11, ctermfg = 0, fg = "#060810" })
hi(0, "Cursor", { bg = "#aeafad", fg = "#554f4a" })
hi(0, "CursorColumn", { bg = "#222222" })
hi(0, "CursorLine", {})
hi(0, "CursorLineNr", { fg = "#bbbbbb" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#34ccb0" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#554f4a" })
hi(0, "DapUIBreakpointsInfo", { fg = "#34ccb0" })
hi(0, "DapUIBreakpointsLine", { fg = "#cf7dc9" })
hi(0, "DapUIBreakpointsPath", { fg = "#cf7dc9" })
hi(0, "DapUICurrentFrameName", { bold = true, fg = "#34ccb0" })
hi(0, "DapUIDecoration", { fg = "#cf7dc9" })
hi(0, "DapUIFloatBorder", { fg = "#cf7dc9" })
hi(0, "DapUILineNumber", { fg = "#cf7dc9" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#cf7dc9" })
hi(0, "DapUIPlayPause", { fg = "#34ccb0" })
hi(0, "DapUIPlayPauseNC", { fg = "#34ccb0" })
hi(0, "DapUIRestart", { fg = "#34ccb0" })
hi(0, "DapUIRestartNC", { fg = "#34ccb0" })
hi(0, "DapUIScope", { fg = "#cf7dc9" })
hi(0, "DapUISource", { fg = "#14a2ff" })
hi(0, "DapUIStepBack", { fg = "#cf7dc9" })
hi(0, "DapUIStepBackNC", { fg = "#cf7dc9" })
hi(0, "DapUIStepInto", { fg = "#cf7dc9" })
hi(0, "DapUIStepIntoNC", { fg = "#cf7dc9" })
hi(0, "DapUIStepOut", { fg = "#cf7dc9" })
hi(0, "DapUIStepOutNC", { fg = "#cf7dc9" })
hi(0, "DapUIStepOver", { fg = "#cf7dc9" })
hi(0, "DapUIStepOverNC", { fg = "#cf7dc9" })
hi(0, "DapUIStop", { fg = "#fe343c" })
hi(0, "DapUIStopNC", { fg = "#fe343c" })
hi(0, "DapUIStoppedThread", { fg = "#cf7dc9" })
hi(0, "DapUIThread", { fg = "#34ccb0" })
hi(0, "DapUIType", { fg = "#cf7dc9" })
hi(0, "DapUIUnavailable", { fg = "#554f4a" })
hi(0, "DapUIUnavailableNC", { fg = "#554f4a" })
hi(0, "DapUIWatchesEmpty", { fg = "#554f4a" })
hi(0, "DapUIWatchesError", { fg = "#fe343c" })
hi(0, "DapUIWatchesValue", { fg = "#34ccb0" })
hi(0, "DapUIWinSelect", { bold = true, fg = "#cf7dc9" })
hi(0, "DashboardDesc", { fg = "#dcb96e" })
hi(0, "DashboardFooter", { fg = "#489ce0", italic = true })
hi(0, "DashboardHeader", { fg = "#489ce0" })
hi(0, "DashboardIcon", { fg = "#dcb96e" })
hi(0, "DashboardShortCut", { fg = "#cf7dc9" })
hi(0, "Debug", { fg = "#d4d4d4" })
hi(0, "Define", { fg = "#cf7dc9" })
hi(0, "Delimiter", { fg = "#d4d4d4" })
hi(0, "DiagnosticError", { fg = "#fe343c" })
hi(0, "DiagnosticHint", { fg = "#489ce0" })
hi(0, "DiagnosticInfo", { fg = "#489ce0" })
hi(0, "DiagnosticOk", { fg = "#34ccb0" })
hi(0, "DiagnosticUnderlineError", { sp = "#f44747", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#569cd6", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#569cd6", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#dcdcaa", undercurl = true })
hi(0, "DiagnosticUnnecessary", { fg = "#689eba" })
hi(0, "DiagnosticWarn", { fg = "#dddd9b" })
hi(0, "DiffAdd", { bg = "#4b5632" })
hi(0, "DiffChange", { bg = "#4b1818" })
hi(0, "DiffDelete", { bg = "#6f1313" })
hi(0, "DiffText", { bg = "#6f1313" })
hi(0, "Directory", { fg = "#489ce0" })
hi(0, "EndOfBuffer", {})
hi(0, "Error", { fg = "#fe343c", sp = "#f44747", undercurl = true })
hi(0, "ErrorMsg", { fg = "#fe343c" })
hi(0, "Exception", { fg = "#cf7dc9" })
hi(0, "EyelinerDimmed", { fg = "#639b49" })
hi(0, "EyelinerPrimary", { fg = "#489ce0" })
hi(0, "EyelinerSecondary", { fg = "#cf7dc9" })
hi(0, "Float", { fg = "#aed19b" })
hi(0, "FocusedSymbol", { bg = "#084671", fg = "#ffffff" })
hi(0, "FoldColumn", { fg = "#5a5a5a" })
hi(0, "Folded", { bg = "#202d39" })
hi(0, "Function", { fg = "#dddd9b" })
hi(0, "GitGutterAdd", { fg = "#639b49" })
hi(0, "GitGutterChange", { fg = "#dddd9b" })
hi(0, "GitGutterDelete", { fg = "#fe343c" })
hi(0, "GitSignsAdd", { fg = "#639b49" })
hi(0, "GitSignsAddLn", { bg = "#6a9955" })
hi(0, "GitSignsChange", { fg = "#dddd9b" })
hi(0, "GitSignsChangeLn", { bg = "#dcdcaa" })
hi(0, "GitSignsDelete", { fg = "#fe343c" })
hi(0, "GitSignsDeleteLn", { bg = "#f44747" })
hi(0, "GitSignsStagedAdd", { fg = "#324d24" })
hi(0, "GitSignsStagedAddCul", { fg = "#324d24" })
hi(0, "GitSignsStagedAddLn", { bg = "#6a9955" })
hi(0, "GitSignsStagedAddNr", { fg = "#324d24" })
hi(0, "GitSignsStagedChange", { fg = "#6f6e4d" })
hi(0, "GitSignsStagedChangeCul", { fg = "#6f6e4d" })
hi(0, "GitSignsStagedChangeLn", { bg = "#dcdcaa" })
hi(0, "GitSignsStagedChangeNr", { fg = "#6f6e4d" })
hi(0, "GitSignsStagedChangedelete", { fg = "#6f6e4d" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#6f6e4d" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#dcdcaa" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#6f6e4d" })
hi(0, "GitSignsStagedDelete", { fg = "#801a1d" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#801a1d" })
hi(0, "GitSignsStagedDeleteLn", { bg = "#f44747" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#801a1d" })
hi(0, "GitSignsStagedTopdelete", { fg = "#801a1d" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#801a1d" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#801a1d" })
hi(0, "Identifier", { fg = "#98dcff" })
hi(0, "Ignore", { fg = "#d4d4d4" })
hi(0, "IlluminatedWordRead", { bg = "#343b41" })
hi(0, "IlluminatedWordText", { bg = "#343b41" })
hi(0, "IlluminatedWordWrite", { bg = "#343b41" })
hi(0, "IncSearch", { bg = "#515c6a" })
hi(0, "Include", { fg = "#cf7dc9" })
hi(0, "IndentBlanklineChar", { fg = "#404040", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#707070", nocombine = true })
hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#707070", underline = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#404040", nocombine = true })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#404040", nocombine = true })
hi(0, "Keyword", { fg = "#cf7dc9" })
hi(0, "LSPSagaDiagnosticTruncateLine", { fg = "#5a5a5a" })
hi(0, "Label", { fg = "#cf7dc9" })
hi(0, "LineNr", { fg = "#5a5a5a" })
hi(0, "LspFloatWinBorder", { fg = "#5a5a5a" })
hi(0, "LspFloatWinNormal", { fg = "#d4d4d4" })
hi(0, "LspInfoBorder", { fg = "#5a5a5a" })
hi(0, "LspLinesDiagBorder", { fg = "#5a5a5a" })
hi(0, "LspReferenceRead", { bg = "#343b41" })
hi(0, "LspReferenceText", { bg = "#343b41" })
hi(0, "LspReferenceWrite", { bg = "#343b41" })
hi(0, "LspSagaBorderTitle", { fg = "#554f4a" })
hi(0, "LspSagaCodeActionBorder", { fg = "#5a5a5a" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#5a5a5a" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#5a5a5a" })
hi(0, "LspSagaDocTruncateLine", { fg = "#5a5a5a" })
hi(0, "LspSagaHoverBorder", { fg = "#5a5a5a" })
hi(0, "LspSagaLspFinderBorder", { fg = "#5a5a5a" })
hi(0, "LspSagaRenameBorder", { fg = "#5a5a5a" })
hi(0, "LspSagaShTruncateLine", { fg = "#5a5a5a" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#5a5a5a" })
hi(0, "Macro", { fg = "#cf7dc9" })
hi(0, "MarkviewBlockQuoteDefault", { fg = "#639b49" })
hi(0, "MarkviewBlockQuoteError", { fg = "#fe343c" })
hi(0, "MarkviewBlockQuoteNote", { fg = "#34ccb0" })
hi(0, "MarkviewBlockQuoteOk", { fg = "#34ccb0" })
hi(0, "MarkviewBlockQuoteSpecial", { fg = "#cf7dc9" })
hi(0, "MarkviewBlockQuoteWarn", { fg = "#dddd9b" })
hi(0, "MarkviewCheckboxCancelled", { fg = "#639b49" })
hi(0, "MarkviewCheckboxChecked", { fg = "#34ccb0" })
hi(0, "MarkviewCheckboxPending", { fg = "#dddd9b" })
hi(0, "MarkviewCheckboxProgress", { fg = "#cf7dc9" })
hi(0, "MarkviewCheckboxStriked", { fg = "#639b49", strikethrough = true })
hi(0, "MarkviewCheckboxUnchecked", { fg = "#fe343c" })
hi(0, "MarkviewCode", { bg = "#28283d" })
hi(0, "MarkviewCodeInfo", { bg = "#28283d", fg = "#639b49" })
hi(0, "MarkviewGradient1", { fg = "#cbd6f9" })
hi(0, "MarkviewGradient10", { fg = "#84b4ff" })
hi(0, "MarkviewGradient2", { fg = "#c3d2f9" })
hi(0, "MarkviewGradient3", { fg = "#bacefb" })
hi(0, "MarkviewGradient4", { fg = "#b3cafc" })
hi(0, "MarkviewGradient5", { fg = "#abc6fc" })
hi(0, "MarkviewGradient6", { fg = "#a3c3fe" })
hi(0, "MarkviewGradient7", { fg = "#9bbfff" })
hi(0, "MarkviewGradient8", { fg = "#94bbff" })
hi(0, "MarkviewGradient9", { fg = "#8bb7ff" })
hi(0, "MarkviewHeading1", { bg = "#2c3d58", fg = "#489ce0" })
hi(0, "MarkviewHeading1Sign", { fg = "#489ce0" })
hi(0, "MarkviewHeading2", { bg = "#2c3d58", fg = "#489ce0" })
hi(0, "MarkviewHeading2Sign", { fg = "#489ce0" })
hi(0, "MarkviewHeading3", { bg = "#2c3d58", fg = "#489ce0" })
hi(0, "MarkviewHeading3Sign", { fg = "#489ce0" })
hi(0, "MarkviewHeading4", { bg = "#2c3d58", fg = "#489ce0" })
hi(0, "MarkviewHeading4Sign", { fg = "#489ce0" })
hi(0, "MarkviewHeading5", { bg = "#2c3d58", fg = "#489ce0" })
hi(0, "MarkviewHeading5Sign", { fg = "#489ce0" })
hi(0, "MarkviewHeading6", { bg = "#2c3d58", fg = "#489ce0" })
hi(0, "MarkviewHeading6Sign", { fg = "#489ce0" })
hi(0, "MarkviewIcon1", { bg = "#28283d", fg = "#489ce0" })
hi(0, "MarkviewIcon1Fg", { fg = "#489ce0" })
hi(0, "MarkviewIcon1Sign", { fg = "#489ce0" })
hi(0, "MarkviewIcon2", { bg = "#28283d", fg = "#489ce0" })
hi(0, "MarkviewIcon2Fg", { fg = "#489ce0" })
hi(0, "MarkviewIcon2Sign", { fg = "#489ce0" })
hi(0, "MarkviewIcon3", { bg = "#28283d", fg = "#489ce0" })
hi(0, "MarkviewIcon3Fg", { fg = "#489ce0" })
hi(0, "MarkviewIcon3Sign", { fg = "#489ce0" })
hi(0, "MarkviewIcon4", { bg = "#28283d", fg = "#489ce0" })
hi(0, "MarkviewIcon4Fg", { fg = "#489ce0" })
hi(0, "MarkviewIcon4Sign", { fg = "#489ce0" })
hi(0, "MarkviewIcon5", { bg = "#28283d", fg = "#489ce0" })
hi(0, "MarkviewIcon5Fg", { fg = "#489ce0" })
hi(0, "MarkviewIcon5Sign", { fg = "#489ce0" })
hi(0, "MarkviewIcon6", { bg = "#28283d", fg = "#489ce0" })
hi(0, "MarkviewIcon6Fg", { fg = "#489ce0" })
hi(0, "MarkviewIcon6Sign", { fg = "#489ce0" })
hi(0, "MarkviewInlineCode", { bg = "#32324c" })
hi(0, "MarkviewLatexSubscript", { fg = "#a59371", italic = true })
hi(0, "MarkviewLatexSuperscript", { fg = "#66976c", italic = true })
hi(0, "MarkviewListItemMinus", { fg = "#dddd9b" })
hi(0, "MarkviewListItemPlus", { fg = "#34ccb0" })
hi(0, "MarkviewListItemStar", { fg = "#34ccb0" })
hi(0, "MarkviewTableAlignCenter", { fg = "#489ce0" })
hi(0, "MarkviewTableAlignLeft", { fg = "#489ce0" })
hi(0, "MarkviewTableAlignRight", { fg = "#489ce0" })
hi(0, "MarkviewTableBorder", { fg = "#34ccb0" })
hi(0, "MarkviewTableHeader", { fg = "#489ce0" })
hi(0, "MatchParen", { bg = "#51504f" })
hi(0, "MiniStatuslineDevinfo", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "MiniStatuslineFileinfo", { bg = "#636369", fg = "#d4d4d4" })
hi(0, "MiniStatuslineFilename", { bg = "#373737", fg = "#d4d4d4" })
hi(0, "MiniStatuslineInactive", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "MiniStatuslineModeCommand", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "MiniStatuslineModeInsert", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "MiniStatuslineModeNormal", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "MiniStatuslineModeOther", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "MiniStatuslineModeReplace", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "MiniStatuslineModeVisual", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "ModeMsg", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "MoreMsg", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "NeoTreeBufferNumber", { fg = "#5a5a5a" })
hi(0, "NeoTreeCursorLine", { bg = "#222222" })
hi(0, "NeoTreeDimText", { bg = "#222222" })
hi(0, "NeoTreeDirectoryIcon", { fg = "#489ce0" })
hi(0, "NeoTreeDirectoryName", { fg = "#d4d4d4" })
hi(0, "NeoTreeDotfile", { fg = "#689eba" })
hi(0, "NeoTreeFileIcon", { fg = "#6263a4" })
hi(0, "NeoTreeFileName", { fg = "#d4d4d4" })
hi(0, "NeoTreeFileNameOpened", { bg = "#222222", fg = "#d4d4d4" })
hi(0, "NeoTreeFilterTerm", { fg = "#d4d4d4" })
hi(0, "NeoTreeFloatBorder", { fg = "#5a5a5a" })
hi(0, "NeoTreeFloatTitle", { fg = "#5a5a5a" })
hi(0, "NeoTreeTitleBar", { fg = "#5a5a5a" })
hi(0, "NeogitDiffAdd", { bg = "#373d29", fg = "#76bb84" })
hi(0, "NeogitDiffAddCursor", { link = "NeogitDiffAddHighlight" })
hi(0, "NeogitDiffAddHighlight", { bg = "#4b5632", fg = "#76bb84" })
hi(0, "NeogitDiffContext", { bg = "#252526", fg = "#bbbbbb" })
hi(0, "NeogitDiffContextCursor", { link = "NeogitDiffContextHighlight" })
hi(0, "NeogitDiffContextHighlight", { bg = "#373737", fg = "#bbbbbb" })
hi(0, "NeogitDiffDelete", { bg = "#4b1818", fg = "#d0432c" })
hi(0, "NeogitDiffDeleteCursor", { link = "NeogitDiffDeleteHighlight" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#6f1313", fg = "#d0432c" })
hi(0, "NeogitDiffHeader", { fg = "#898989" })
hi(0, "NeogitDiffHeaderHighlight", { fg = "#898989" })
hi(0, "NeogitHunkHeader", { bg = "#252526", fg = "#e8be7f" })
hi(0, "NeogitHunkHeaderCursor", { link = "NeogitHunkHeaderHighlight" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#373737", fg = "#e8be7f" })
hi(0, "NeogitWinSeparator", { link = "WinSeparator" })
hi(0, "NeotestAdapterName", { bold = true, fg = "#d4d4d4" })
hi(0, "NeotestDir", { fg = "#489ce0" })
hi(0, "NeotestExpandMarker", { fg = "#554f4a" })
hi(0, "NeotestFailed", { fg = "#fe343c" })
hi(0, "NeotestFile", { fg = "#489ce0" })
hi(0, "NeotestFocused", { bold = true })
hi(0, "NeotestIndent", { fg = "#554f4a" })
hi(0, "NeotestMarked", { bold = true, fg = "#dcb96e" })
hi(0, "NeotestNamespace", { fg = "#cf7dc9" })
hi(0, "NeotestPassed", { fg = "#34ccb0" })
hi(0, "NeotestRunning", { fg = "#ffd601" })
hi(0, "NeotestSkipped", { fg = "#489ce0" })
hi(0, "NeotestTarget", { fg = "#dc5f62" })
hi(0, "NeotestWatching", { fg = "#ffd601" })
hi(0, "NeotestWinSelect", { bold = true, fg = "#489ce0" })
hi(0, "NonText", { fg = "#5a5a5a" })
hi(0, "Normal", { fg = "#d4d4d4" })
hi(0, "NormalFloat", { bg = "#272727" })
hi(0, "Number", { fg = "#aed19b" })
hi(0, "NvimTreeCursorLine", { bg = "#373737" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#808080" })
hi(0, "NvimTreeEndOfBuffer", { fg = "#24242d" })
hi(0, "NvimTreeFolderIcon", { fg = "#489ce0" })
hi(0, "NvimTreeFolderName", { fg = "#d4d4d4" })
hi(0, "NvimTreeGitDeleted", { fg = "#d0432c" })
hi(0, "NvimTreeGitDirty", { fg = "#e8be7f" })
hi(0, "NvimTreeGitIgnored", { fg = "#8c8c8c" })
hi(0, "NvimTreeGitMerge", { fg = "#64cc8b" })
hi(0, "NvimTreeGitNew", { fg = "#76bb84" })
hi(0, "NvimTreeGitRenamed", { fg = "#64cc8b" })
hi(0, "NvimTreeGitStaged", { fg = "#e8be7f" })
hi(0, "NvimTreeImageFile", { fg = "#6263a4" })
hi(0, "NvimTreeIndentMarker", { fg = "#5a5a5a" })
hi(0, "NvimTreeNormal", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "NvimTreeOpenedFolderName", { bg = "#252526" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#d4d4d4" })
hi(0, "NvimTreeSpecialFile", { fg = "#cf7dc9", underline = true })
hi(0, "Operator", { fg = "#d4d4d4" })
hi(0, "Pmenu", { bg = "#272727", fg = "#bbbbbb" })
hi(0, "PmenuSbar", { bg = "#343b41" })
hi(0, "PmenuSel", { bg = "#004b72", fg = "#bbbbbb" })
hi(0, "PmenuThumb", { bg = "#bbbbbb" })
hi(0, "PreProc", { fg = "#cf7dc9" })
hi(0, "Question", { fg = "#489ce0" })
hi(0, "QuickFixLine", { bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#14a2ff" })
hi(0, "RainbowDelimiterCyan", { fg = "#34ccb0" })
hi(0, "RainbowDelimiterGreen", { fg = "#639b49" })
hi(0, "RainbowDelimiterOrange", { fg = "#d78c6d" })
hi(0, "RainbowDelimiterRed", { fg = "#cf7dc9" })
hi(0, "RainbowDelimiterViolet", { fg = "#6263a4" })
hi(0, "RainbowDelimiterYellow", { fg = "#dcb96e" })
hi(0, "Removed", { ctermfg = 9, fg = "#ffbdb6" })
hi(0, "Repeat", { fg = "#cf7dc9" })
hi(0, "Search", { bg = "#613315" })
hi(0, "SignColumn", {})
hi(0, "Special", { fg = "#dcb96e" })
hi(0, "SpecialChar", { fg = "#d4d4d4" })
hi(0, "SpecialComment", { fg = "#639b49" })
hi(0, "SpecialKey", { fg = "#489ce0" })
hi(0, "SpellBad", { sp = "#f44747", undercurl = true })
hi(0, "SpellCap", { sp = "#dcdcaa", undercurl = true })
hi(0, "SpellLocal", { sp = "#569cd6", undercurl = true })
hi(0, "SpellRare", { sp = "#646695", undercurl = true })
hi(0, "Statement", { fg = "#cf7dc9" })
hi(0, "StatusLine", { fg = "#d4d4d4" })
hi(0, "StatusLineNC", { fg = "#d4d4d4" })
hi(0, "StorageClass", { fg = "#489ce0" })
hi(0, "String", { fg = "#d78c6d" })
hi(0, "Structure", { fg = "#34ccb0" })
hi(0, "SymbolsOutlineConnector", { fg = "#5a5a5a" })
hi(0, "TabLine", { bg = "#2d2d2d", fg = "#d4d4d4" })
hi(0, "TabLineFill", { bg = "#252526", fg = "#d4d4d4" })
hi(0, "TabLineSel", { bg = "#1f1f1f", fg = "#d4d4d4" })
hi(0, "Tag", { fg = "#d4d4d4" })
hi(0, "TelescopeMatching", { bold = true, fg = "#14a2ff" })
hi(0, "TelescopeMultiSelection", { bg = "#004b72", fg = "#d4d4d4" })
hi(0, "TelescopeNormal", { fg = "#d4d4d4" })
hi(0, "TelescopePreviewBorder", { fg = "#5a5a5a" })
hi(0, "TelescopePromptBorder", { fg = "#5a5a5a" })
hi(0, "TelescopePromptPrefix", { fg = "#d4d4d4" })
hi(0, "TelescopeResultsBorder", { fg = "#5a5a5a" })
hi(0, "TelescopeSelection", { bg = "#004b72", fg = "#d4d4d4" })
hi(0, "Title", { bold = true })
hi(0, "Todo", { bold = true, fg = "#dcb96e" })
hi(0, "TodoBgFIX", { bg = "#f44747", bold = true, fg = "#000000" })
hi(0, "TodoBgHACK", { bg = "#dcdcaa", bold = true, fg = "#000000" })
hi(0, "TodoBgNOTE", { bg = "#569cd6", bold = true, fg = "#000000" })
hi(0, "TodoBgPERF", { bg = "#9cdcfe", bold = true, fg = "#000000" })
hi(0, "TodoBgTEST", { bg = "#9cdcfe", bold = true, fg = "#000000" })
hi(0, "TodoBgTODO", { bg = "#569cd6", bold = true, fg = "#000000" })
hi(0, "TodoBgWARN", { bg = "#dcdcaa", bold = true, fg = "#000000" })
hi(0, "TodoFgFIX", { fg = "#fe343c" })
hi(0, "TodoFgHACK", { fg = "#dddd9b" })
hi(0, "TodoFgNOTE", { fg = "#489ce0" })
hi(0, "TodoFgPERF", { fg = "#98dcff" })
hi(0, "TodoFgTEST", { fg = "#98dcff" })
hi(0, "TodoFgTODO", { fg = "#489ce0" })
hi(0, "TodoFgWARN", { fg = "#dddd9b" })
hi(0, "TodoSignFIX", { fg = "#fe343c" })
hi(0, "TodoSignHACK", { fg = "#dddd9b" })
hi(0, "TodoSignNOTE", { fg = "#489ce0" })
hi(0, "TodoSignPERF", { fg = "#98dcff" })
hi(0, "TodoSignTEST", { fg = "#98dcff" })
hi(0, "TodoSignTODO", { fg = "#489ce0" })
hi(0, "TodoSignWARN", { fg = "#dddd9b" })
hi(0, "TroubleNormal", { link = "Normal" })
hi(0, "TroubleNormalNC", { link = "Normal" })
hi(0, "Type", { fg = "#489ce0" })
hi(0, "Typedef", { fg = "#489ce0" })
hi(0, "VertSplit", { fg = "#444444" })
hi(0, "Visual", { bg = "#264f78" })
hi(0, "VisualNOS", { bg = "#264f78" })
hi(0, "WarningMsg", { bold = true, fg = "#fe343c" })
hi(0, "Whitespace", { fg = "#5a5a5a" })
hi(0, "WildMenu", { bg = "#264f78" })
hi(0, "WilderWildmenuAccent", { bold = true, fg = "#d4d4d4", underline = true })
hi(0, "WilderWildmenuSelectedAccent", { bg = "#264f78", bold = true, underline = true })
hi(0, "WinBar", { bold = true, fg = "#d4d4d4" })
hi(0, "WinBarNC", { fg = "#d4d4d4" })
hi(0, "WinSeparator", { link = "VertSplit" })
hi(0, "asciidocAdmonition", { fg = "#d78c6d" })
hi(0, "asciidocAttributeEntry", { fg = "#dcb96e" })
hi(0, "asciidocAttributeList", { fg = "#cf7dc9" })
hi(0, "asciidocAttributeRef", { fg = "#dcb96e" })
hi(0, "asciidocBackslash", { link = "Keyword" })
hi(0, "asciidocHLabel", { bold = true, fg = "#489ce0" })
hi(0, "asciidocListingBlock", { fg = "#d78c6d" })
hi(0, "asciidocMacro", { fg = "#cf7dc9" })
hi(0, "asciidocMacroAttributes", { fg = "#dcb96e" })
hi(0, "asciidocOneLineTitle", { bold = true, fg = "#489ce0" })
hi(0, "asciidocPassthroughBlock", { fg = "#489ce0" })
hi(0, "asciidocQuotedBold", { link = "markdownBold" })
hi(0, "asciidocQuotedEmphasized", { fg = "#489ce0", italic = true })
hi(0, "asciidocQuotedEmphasized2", { fg = "#489ce0", italic = true })
hi(0, "asciidocQuotedEmphasizedItalic", { fg = "#489ce0", italic = true })
hi(0, "asciidocQuotedMonospaced", { fg = "#d78c6d" })
hi(0, "asciidocQuotedMonospaced2", { link = "asciidocQuotedMonospaced" })
hi(0, "asciidocQuotedUnconstrainedBold", { link = "asciidocQuotedBold" })
hi(0, "asciidocQuotedUnconstrainedEmphasized", { link = "asciidocQuotedEmphasized" })
hi(0, "asciidocTriplePlusPassthrough", { fg = "#dddd9b" })
hi(0, "asciidocURL", { link = "markdownUrl" })
hi(0, "cssAttr", { fg = "#d78c6d" })
hi(0, "cssAttrRegion", { fg = "#d78c6d" })
hi(0, "cssBraces", { fg = "#d4d4d4" })
hi(0, "cssClassName", { fg = "#dcb96e" })
hi(0, "cssColor", { fg = "#d78c6d" })
hi(0, "cssDefinition", { fg = "#98dcff" })
hi(0, "cssFunction", { fg = "#d78c6d" })
hi(0, "cssFunctionName", { fg = "#d78c6d" })
hi(0, "cssIdentifier", { fg = "#dcb96e" })
hi(0, "cssImportant", { fg = "#489ce0" })
hi(0, "cssInclude", { fg = "#cf7dc9" })
hi(0, "cssProp", { fg = "#98dcff" })
hi(0, "cssPseudoClass", { fg = "#dcb96e" })
hi(0, "cssPseudoClassId", { fg = "#dcb96e" })
hi(0, "cssPseudoClassLang", { fg = "#dcb96e" })
hi(0, "cssStyle", { fg = "#98dcff" })
hi(0, "cssTagName", { fg = "#dcb96e" })
hi(0, "cssUnitDecorators", { fg = "#d78c6d" })
hi(0, "cssValueLength", { fg = "#d78c6d" })
hi(0, "cssValueNumber", { fg = "#d78c6d" })
hi(0, "cssVendor", { fg = "#d78c6d" })
hi(0, "debugPC", { bg = "#4c4c19" })
hi(0, "diffAdded", { link = "DiffAdd" })
hi(0, "diffChanged", { link = "DiffChange" })
hi(0, "diffRemoved", { link = "DiffDelete" })
hi(0, "gitcommitBlank", { fg = "#cf7dc9" })
hi(0, "gitcommitBranch", { fg = "#cf7dc9" })
hi(0, "gitcommitComment", { fg = "#808080" })
hi(0, "gitcommitDiscardedFile", { fg = "#fe343c" })
hi(0, "gitcommitDiscardedType", { fg = "#fe343c" })
hi(0, "gitcommitHeader", { fg = "#808080" })
hi(0, "gitcommitOnBranch", { fg = "#808080" })
hi(0, "gitcommitOverflow", { fg = "#fe343c" })
hi(0, "gitcommitSelectedFile", { fg = "#639b49" })
hi(0, "gitcommitSelectedType", { fg = "#639b49" })
hi(0, "gitcommitSummary", { fg = "#cf7dc9" })
hi(0, "goBoolean", { fg = "#489ce0" })
hi(0, "goBuiltins", { fg = "#dddd9b" })
hi(0, "goComplexes", { fg = "#34ccb0" })
hi(0, "goConst", { fg = "#489ce0" })
hi(0, "goDeclType", { fg = "#489ce0" })
hi(0, "goDeclaration", { fg = "#489ce0" })
hi(0, "goFloats", { fg = "#34ccb0" })
hi(0, "goFunctionCall", { fg = "#dddd9b" })
hi(0, "goImport", { fg = "#489ce0" })
hi(0, "goMethodCall", { fg = "#dddd9b" })
hi(0, "goPackage", { fg = "#489ce0" })
hi(0, "goPredefinedIdentifiers", { fg = "#489ce0" })
hi(0, "goReceiver", { fg = "#d4d4d4" })
hi(0, "goReceiverType", { fg = "#d4d4d4" })
hi(0, "goSignedInts", { fg = "#34ccb0" })
hi(0, "goSingleDecl", { fg = "#98dcff" })
hi(0, "goStatement", { fg = "#cf7dc9" })
hi(0, "goTodo", { fg = "#639b49" })
hi(0, "goType", { fg = "#34ccb0" })
hi(0, "goTypeDecl", { fg = "#489ce0" })
hi(0, "goTypeName", { fg = "#34ccb0" })
hi(0, "goUnsignedInts", { fg = "#34ccb0" })
hi(0, "goVar", { fg = "#489ce0" })
hi(0, "goVarAssign", { fg = "#98dcff" })
hi(0, "goVarDefs", { fg = "#98dcff" })
hi(0, "htmlArg", { fg = "#98dcff" })
hi(0, "htmlEndTag", { fg = "#808080" })
hi(0, "htmlSpecialTagName", { fg = "#489ce0" })
hi(0, "htmlTag", { fg = "#808080" })
hi(0, "htmlTagName", { fg = "#489ce0" })
hi(0, "illuminatedCurWord", { bg = "#343b41" })
hi(0, "illuminatedWord", { bg = "#343b41" })
hi(0, "jsClassDefinition", { fg = "#34ccb0" })
hi(0, "jsClassKeyword", { fg = "#489ce0" })
hi(0, "jsDestructuringBlock", { fg = "#98dcff" })
hi(0, "jsExportDefault", { fg = "#cf7dc9" })
hi(0, "jsExtendsKeyword", { fg = "#489ce0" })
hi(0, "jsFuncArgs", { fg = "#98dcff" })
hi(0, "jsFuncBlock", { fg = "#98dcff" })
hi(0, "jsFuncCall", { fg = "#dddd9b" })
hi(0, "jsGlobalObjects", { fg = "#34ccb0" })
hi(0, "jsIfElseBlock", { fg = "#98dcff" })
hi(0, "jsModuleKeyword", { fg = "#98dcff" })
hi(0, "jsObjectKey", { fg = "#98dcff" })
hi(0, "jsObjectProp", { fg = "#98dcff" })
hi(0, "jsObjectValue", { fg = "#98dcff" })
hi(0, "jsOperatorKeyword", { fg = "#489ce0" })
hi(0, "jsParen", { fg = "#98dcff" })
hi(0, "jsParenIfElse", { fg = "#98dcff" })
hi(0, "jsRegexpString", { fg = "#dc5f62" })
hi(0, "jsSpreadExpression", { fg = "#98dcff" })
hi(0, "jsSpreadOperator", { fg = "#98dcff" })
hi(0, "jsThis", { fg = "#489ce0" })
hi(0, "jsVariableDef", { fg = "#98dcff" })
hi(0, "jsonBoolean", { fg = "#489ce0" })
hi(0, "jsonEscape", { fg = "#dcb96e" })
hi(0, "jsonKeyword", { fg = "#98dcff" })
hi(0, "jsonNull", { fg = "#489ce0" })
hi(0, "lCursor", { bg = "#d4d4d4" })
hi(0, "luaBuiltIn", { fg = "#489ce0" })
hi(0, "luaFuncArgName", { fg = "#98dcff" })
hi(0, "luaFuncCall", { fg = "#dddd9b" })
hi(0, "luaFuncKeyword", { fg = "#cf7dc9" })
hi(0, "luaLocal", { fg = "#cf7dc9" })
hi(0, "markdownBold", { bold = true, fg = "#489ce0" })
hi(0, "markdownCode", { fg = "#d78c6d" })
hi(0, "markdownCodeDelimiter", { fg = "#d4d4d4" })
hi(0, "markdownEscape", { fg = "#d78c6d" })
hi(0, "markdownFootnote", { fg = "#d78c6d" })
hi(0, "markdownFootnoteDefinition", { fg = "#d78c6d" })
hi(0, "markdownHeadingDelimiter", { fg = "#489ce0" })
hi(0, "markdownLinkText", { fg = "#d78c6d" })
hi(0, "markdownRule", { bold = true, fg = "#489ce0" })
hi(0, "markdownUrl", { fg = "#d4d4d4", underline = true })
hi(0, "phpClass", { fg = "#34ccb0" })
hi(0, "phpFunction", { fg = "#dddd9b" })
hi(0, "phpInclude", { fg = "#489ce0" })
hi(0, "phpMethod", { fg = "#dddd9b" })
hi(0, "phpMethodsVar", { fg = "#98dcff" })
hi(0, "phpRegion", { fg = "#34ccb0" })
hi(0, "phpStaticClasses", { fg = "#34ccb0" })
hi(0, "phpUseClass", { fg = "#34ccb0" })
hi(0, "pythonBoolean", { fg = "#489ce0" })
hi(0, "pythonBuiltinObj", { fg = "#98dcff" })
hi(0, "pythonBuiltinType", { fg = "#34ccb0" })
hi(0, "pythonClassDef", { fg = "#34ccb0" })
hi(0, "pythonClassVar", { fg = "#489ce0" })
hi(0, "pythonExClass", { fg = "#34ccb0" })
hi(0, "pythonException", { fg = "#cf7dc9" })
hi(0, "pythonNone", { fg = "#489ce0" })
hi(0, "pythonOperator", { fg = "#489ce0" })
hi(0, "pythonStatement", { fg = "#489ce0" })
hi(0, "pythonTodo", { fg = "#489ce0" })
hi(0, "rubyClassName", { fg = "#34ccb0" })
hi(0, "rubyClassNameTag", { fg = "#34ccb0" })
hi(0, "rubyConstant", { fg = "#34ccb0" })
hi(0, "rubyModuleName", { fg = "#34ccb0" })
hi(0, "rustCommentLineDoc", {})
hi(0, "rustDefault", {})
hi(0, "rustEnum", {})
hi(0, "rustEscape", {})
hi(0, "rustModPathSep", {})
hi(0, "rustSigil", {})
hi(0, "rustStringContinuation", {})
hi(0, "rustStructure", {})
hi(0, "shDeref", { fg = "#98dcff" })
hi(0, "shVariable", { fg = "#98dcff" })
hi(0, "sqlFunction", { fg = "#dcb96e" })
hi(0, "sqlKeyword", { fg = "#cf7dc9" })
hi(0, "sqlOperator", { fg = "#cf7dc9" })
hi(0, "texBeginEnd", { fg = "#dddd9b" })
hi(0, "texBeginEndModifier", { fg = "#98dcff" })
hi(0, "texBeginEndName", { fg = "#98dcff" })
hi(0, "texDocType", { fg = "#cf7dc9" })
hi(0, "texDocTypeArgs", { fg = "#98dcff" })
hi(0, "texOption", { fg = "#98dcff" })
hi(0, "texStatement", { fg = "#489ce0" })
hi(0, "typescriptAccessibilityModifier", { fg = "#489ce0" })
hi(0, "typescriptAliasDeclaration", { fg = "#34ccb0" })
hi(0, "typescriptAliasKeyword", { fg = "#489ce0" })
hi(0, "typescriptAmbientDeclaration", { fg = "#489ce0" })
hi(0, "typescriptArray", { fg = "#dddd9b" })
hi(0, "typescriptArrowFunc", { fg = "#489ce0" })
hi(0, "typescriptArrowFuncArg", { fg = "#98dcff" })
hi(0, "typescriptAsyncFuncKeyword", { fg = "#489ce0" })
hi(0, "typescriptBOM", { fg = "#98dcff" })
hi(0, "typescriptBlock", { fg = "#98dcff" })
hi(0, "typescriptBraces", { fg = "#d4d4d4" })
hi(0, "typescriptCall", { fg = "#489ce0" })
hi(0, "typescriptCase", { fg = "#98dcff" })
hi(0, "typescriptCastKeyword", { fg = "#98dcff" })
hi(0, "typescriptClassBlock", { fg = "#98dcff" })
hi(0, "typescriptClassExtends", { fg = "#489ce0" })
hi(0, "typescriptClassHeritage", { fg = "#34ccb0" })
hi(0, "typescriptClassKeyword", { fg = "#489ce0" })
hi(0, "typescriptClassName", { fg = "#34ccb0" })
hi(0, "typescriptConditionalParen", { fg = "#98dcff" })
hi(0, "typescriptDOMDocProp", { fg = "#98dcff" })
hi(0, "typescriptDecorator", { fg = "#dddd9b" })
hi(0, "typescriptDefault", { fg = "#98dcff" })
hi(0, "typescriptDocComment", { fg = "#34ccb0" })
hi(0, "typescriptDocTags", { fg = "#489ce0" })
hi(0, "typescriptES6SetProp", { fg = "#98dcff" })
hi(0, "typescriptEndColons", { fg = "#98dcff" })
hi(0, "typescriptEnum", { fg = "#34ccb0" })
hi(0, "typescriptEnumKeyword", { fg = "#489ce0" })
hi(0, "typescriptExceptions", { fg = "#98dcff" })
hi(0, "typescriptExport", { fg = "#cf7dc9" })
hi(0, "typescriptFuncCallArg", { fg = "#98dcff" })
hi(0, "typescriptFuncComma", { fg = "#98dcff" })
hi(0, "typescriptFuncKeyword", { fg = "#489ce0" })
hi(0, "typescriptFuncTypeArrow", { fg = "#489ce0" })
hi(0, "typescriptGlobal", { fg = "#34ccb0" })
hi(0, "typescriptGlobalMethod", { fg = "#dddd9b" })
hi(0, "typescriptImport", { fg = "#cf7dc9" })
hi(0, "typescriptIndexExpr", { fg = "#98dcff" })
hi(0, "typescriptInterfaceExtends", { fg = "#489ce0" })
hi(0, "typescriptInterfaceHeritage", { fg = "#34ccb0" })
hi(0, "typescriptInterfaceKeyword", { fg = "#489ce0" })
hi(0, "typescriptInterfaceName", { fg = "#34ccb0" })
hi(0, "typescriptLabel", { fg = "#98dcff" })
hi(0, "typescriptLogicSymbols", { fg = "#98dcff" })
hi(0, "typescriptLoopParen", { fg = "#98dcff" })
hi(0, "typescriptMember", { fg = "#dddd9b" })
hi(0, "typescriptMethodAccessor", { fg = "#489ce0" })
hi(0, "typescriptModule", { fg = "#98dcff" })
hi(0, "typescriptObjectLiteral", { fg = "#98dcff" })
hi(0, "typescriptOperator", { fg = "#489ce0" })
hi(0, "typescriptParamImpl", { fg = "#98dcff" })
hi(0, "typescriptParenExp", { fg = "#98dcff" })
hi(0, "typescriptParens", { fg = "#d4d4d4" })
hi(0, "typescriptPredefinedType", { fg = "#34ccb0" })
hi(0, "typescriptPromiseMethod", { fg = "#dddd9b" })
hi(0, "typescriptReserved", { fg = "#cf7dc9" })
hi(0, "typescriptTemplateSB", { fg = "#dcb96e" })
hi(0, "typescriptTemplateSubstitution", { fg = "#98dcff" })
hi(0, "typescriptTypeParameter", { fg = "#34ccb0" })
hi(0, "typescriptTypeReference", { fg = "#34ccb0" })
hi(0, "typescriptVariable", { fg = "#489ce0" })
hi(0, "typescriptVariableDeclaration", { fg = "#98dcff" })
hi(0, "xmlEndTag", { fg = "#489ce0" })
hi(0, "xmlTag", { fg = "#489ce0" })
hi(0, "xmlTagName", { fg = "#489ce0" })
hi(0, "yamlConstant", { fg = "#489ce0" })
hi(0, "yamlKey", { fg = "#489ce0" })

-- Terminal colors
local g = vim.g

g.terminal_color_1 = "#f44747"
g.terminal_color_2 = "#6a9955"
g.terminal_color_3 = "#dcdcaa"
g.terminal_color_4 = "#569cd6"
g.terminal_color_5 = "#c586c0"
g.terminal_color_6 = "#4ec9b0"
g.terminal_color_7 = "#d4d4d4"
g.terminal_color_8 = "#808080"
g.terminal_color_9 = "#f44747"
g.terminal_color_10 = "#6a9955"
g.terminal_color_11 = "#dcdcaa"
g.terminal_color_12 = "#569cd6"
g.terminal_color_13 = "#c586c0"
g.terminal_color_14 = "#4ec9b0"
g.terminal_color_15 = "#d4d4d4"
